# Experiment 05 — scoring, selection and cash deployment

Based on [04-opt-score-matrix.ipynb](04-opt-score-matrix.ipynb), with execution and accounting from `hyper-ai-v11.py`.

## Goal

Beat the earlier hand-picked 60% 360-day CAGR / 40% 45-day Sortino formula through better scoring, selection and cash usage. Check whether additional features add forward information, whether clips erase useful distinctions, and whether the apparent improvements survive ties, data-quality checks and concentrated profit attribution.

## Method

Use a bounded, predeclared grid of **18 score calibrations**, with six positions and 90-day inverse-variance sizing fixed. Vary CAGR caps 50/100/200% independently from Sortino caps 3/7/12; retain exact 45-day and near-original 46-day controls; compare the previous blended curve and smooth saturation. Separate ratio-floor and missing-component policies. An activity filter is a distinct treatment.

Compare original and blended scores with and without redistribution after blocked top-ups. Redistribution uses only the selected six vaults, preserves deposit checks, settlement obligations, the 98% budget and 33% concentration/TVL limits, and passes targets through normal trade generation. Test feasible-entrant checking, replacement hurdles and five predeclared tie-order seeds separately.

Feature diagnostics use completed T−1 data and per-date cross-sectional relationships with subsequent 14/30/60-day NAV returns. Include Sharpe, Sortino, CAGR, drawdown and Calmar over nine searchable windows. Future labels cannot cross the report end. The indicator inclusion list, return gate, quarantine rules and recorded guard whitelist define the diagnostic universe; individual portfolio exclusions and deposit availability can further restrict executable entries. Plot score-bin outcomes and per-date correlations, and audit coverage and saturation.

Default charts, performance tables and Markdown summaries use **2026-01-01 → 2026-10-05 (end exclusive, UTC)**. Pre-January observations remain available for indicators. Six predeclared controls/treatments also run over all available history; those results remain in separate artefacts. Quarterly comparisons are temporal stability diagnostics, not independent validation. The dataset is frozen when this notebook first loads it; source and guard fingerprints accompany the snapshot. A new source control is mandatory because the current archive can differ from experiment 04.

## Interpretation

Every backtest begins with \$150,000 and no positions. Source fees, gates, execution bands and settlement rules remain in force. Selection changes are research-only compiled functions; no production module is edited. Missing values and the original risk floor are varied separately. The experiment is exploratory and does not establish a prospective winner; historical universe and availability data remain incomplete. Tie seeds are robustness diagnostics, not optimisation candidates.

## Key new insights

- **Same-data benchmark:** the fresh original-formula control has 41.20% CAGR, 1.96 Sharpe and -6.40% maximum drawdown. It reproduces source v11 equity and every trade.
- **Highest observed CAGR:** Feasible entrants gives 41.83% CAGR, 1.99 Sharpe and -6.39% drawdown. This ranking excludes tie-seed diagnostics.
- **Highest observed Sharpe:** Blend 46d gives 2.12 Sharpe and 41.38% CAGR. 3 tested treatment rows improve CAGR and Sharpe with no worse drawdown than the current control; equivalent paths may repeat.
- **Clipping ties:** 39.1% of baseline funded observations have maximum composite score; 63.3% of decisions fund at least two such vaults. Tie ordering must be treated as a robustness check.
- **Benchmark discrepancy:** Restored leader-share/cap inputs and merged readers return 41.20% CAGR versus the earlier 41.59%, closing most of the preceding 33.47% gap. The first 558 chronological trades match the earlier source exactly; remaining differences start in September. See the restored-data rerun report.

## Summary of results

### Matched strategy comparisons — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Completed real engine backtests with six inverse-variance positions. Includes the source-equivalent control, predeclared scoring/cash pairs and the strongest observed treatment; tie seeds are excluded from winner selection. All metrics are net of source-modelled costs.

| Configuration | CAGR | Sharpe | Maximum drawdown | Mean cash weight | Trades |
| --- | --- | --- | --- | --- | --- |
| Hard C1 S3 | 41.20% | 1.96 | -6.40% | 8.83% | 581 |
| Blend 46d | 41.38% | 2.12 | -4.85% | 7.43% | 583 |
| Smooth C1 S3 | 31.64% | 1.65 | -5.28% | 5.42% | 628 |
| Hard C1 S3 / refill | 39.56% | 1.88 | -6.44% | 8.40% | 585 |
| Blend 46d / refill | 40.00% | 2.05 | -5.08% | 7.12% | 584 |
| Smooth C1 S3 / refill | 29.65% | 1.54 | -6.01% | 5.24% | 629 |
| Feasible entrants | 41.83% | 1.99 | -6.39% | 8.83% | 571 |

## Robustness of results

The 18 score calibrations, 11 mechanism diagnostics and 6 predeclared full-history confirmations completed. Default tables and charts use the 2026 period; full-history performance is retained separately. Results are exploratory comparisons over previously inspected history, not an untouched holdout. Feature labels use strictly future NAV outcomes, are censored at the report end and are never used to tune backtest parameters in this notebook. Feature IC uncertainty bands resample overlapping decision dates in blocks and remain exploratory.

Source replication passes the equity and complete-ledger checks. Every backtest holds at most six vaults. Refill targets remain within the source fresh budget and concentration/TVL ceilings; deposit checks, pinned holdings and ordinary execution bands can prevent intended dollars from becoming realised exposure. Position attribution reconciles to equity with a largest residual of 8.00e-11 USD.

- **Hard C1 S3:** leading vault Realist Capital supplies 44.8% of positive vault profits. Best day 2026-06-26 returns 6.89%; excess kurtosis 13.67. Zeroing that return gives Sharpe 1.62; removing the leader PnL on the fixed ledger gives Sharpe 1.10. These sensitivities retain the original trading path.
- **Feasible entrants:** leading vault Realist Capital supplies 44.8% of positive vault profits. Best day 2026-06-26 returns 6.88%; excess kurtosis 13.68. Zeroing that return gives Sharpe 1.65; removing the leader PnL on the fixed ledger gives Sharpe 1.13. These sensitivities retain the original trading path.
- **Blend 46d:** leading vault Realist Capital supplies 31.6% of positive vault profits. Best day 2026-06-26 returns 6.77%; excess kurtosis 16.75. Zeroing that return gives Sharpe 1.79; removing the leader PnL on the fixed ledger gives Sharpe 1.49. These sensitivities retain the original trading path.

- **Hard C1 S3 / refill:** mean recovered target is 0.36% of fresh budget, on 18 decisions; realised mean cash is 8.40%. A target-budget recovery is not a guaranteed reduction in realised cash.
- **Blend 46d / refill:** mean recovered target is 0.28% of fresh budget, on 12 decisions; realised mean cash is 7.12%. A target-budget recovery is not a guaranteed reduction in realised cash.
- **Smooth C1 S3 / refill:** mean recovered target is 0.14% of fresh budget, on 11 decisions; realised mean cash is 5.24%. A target-budget recovery is not a guaranteed reduction in realised cash.

The expanded attribution tables show the largest days alongside matching Binance BTC/ETH intervals and curator annotations. Gross NAV labels do not include the strategy's redemption costs. Flat or carried NAV, weak long-window coverage, current membership/guard assumptions and incomplete historical deposit permissions can affect feature diagnostics. The clip, selector and tie grid is bounded; no claim of a global optimum is made.

### Restored leader history rerun — 7 October 2026

This execution uses the freshly downloaded, pinned repaired dataset and the merged leader-share and recorded-cap readers. Strategy settings, searches and period boundaries are unchanged. Historical benchmark differences are displayed separately from mandatory source/control equality on the same inputs. Generated results are isolated under `_artifacts-restored-2026-10-07/05`.

In [1]:
from pathlib import Path
import sys
RESEARCH_DIR=Path("/Users/moo/code/getting-started/scratchpad/hyperliquid-vov-2nd")
sys.path.insert(0,str(RESEARCH_DIR))
from score_matrix_visualisation import compact_output, chart_intro, present_table, metric_table, show_static, with_backtest_period
with compact_output('Experiment 05 setup'):
    import datetime
    import hashlib
    import importlib.util
    import json
    import os
    from copy import deepcopy
    import numpy as np
    import pandas as pd
    import plotly.express as px
    from IPython.display import display
    from dotenv import load_dotenv
    from tqdm_loggable.auto import tqdm
    from tradingstrategy.client import Client
    from tradeexecutor.strategy.parameters import StrategyParameters
    from tradeexecutor.strategy.execution_context import notebook_execution_context
    from tradeexecutor.utils.notebook import setup_charting_and_output, OutputMode
    from score_calibration_experiment import (Calibration, configurations, load_snapshot, ExperimentPanel, CalibrationBacktester, scores, feature_audit)
    from score_matrix import FEATURES, PERIODS
    load_dotenv(override=True)
    setup_charting_and_output(OutputMode.static,image_format="png",width=1500,height=900)
    STRATEGY_PATH=Path("/Users/moo/code/strategies/strategy/hyper-ai-v11.py")
    GUARD_PATH=Path("/Users/moo/code/strategies/deploy/hyper-ai-v10-new-guard-vault-info.json")
    os.environ['HYPER_AI_GUARD_CONFIG_FILE']=str(GUARD_PATH)
    spec=importlib.util.spec_from_file_location('hyper_ai_v11_experiment_05',STRATEGY_PATH)
    strategy=importlib.util.module_from_spec(spec)
    spec.loader.exec_module(strategy)
    parameters=StrategyParameters.from_class(strategy.Parameters)
    chart_start=datetime.datetime(2026,1,1)
    chart_end=parameters.backtest_end
    CHART_PERIOD=f'{chart_start:%Y-%m-%d} → {chart_end:%Y-%m-%d} (end exclusive, UTC)'
    ARTIFACT_DIR=RESEARCH_DIR/'_artifacts-restored-2026-10-07/05'
    ARTIFACT_DIR.mkdir(parents=True,exist_ok=True)
    client=Client.create_jupyter_client()
    score_jobs,mechanism_jobs,long_jobs=configurations()
    baseline=next(c for c in score_jobs if c.name=='Hard C1 S3')
    present_table(pd.DataFrame([c.__dict__ for c in score_jobs]),'Predeclared scoring grid','18 controlled calibrations: coefficients remain 60/40, with six inverse-variance positions. Hard scales are clips; smooth scales are half-saturation points. Missing-component filling and ratio floors are independent.',CHART_PERIOD,collapsed=True)
    present_table(pd.DataFrame([c.__dict__ for c in mechanism_jobs]),'Cash and selector treatments','Refill, feasible-entrant checks, replacement hurdles and seeded exact-score tie orderings. Each row changes its named mechanism relative to the stated scoring curve.',CHART_PERIOD,collapsed=True)

Experiment 05 setup — complete

### Predeclared scoring grid — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

18 controlled calibrations: coefficients remain 60/40, with six inverse-variance positions. Hard scales are clips; smooth scales are half-saturation points. Missing-component filling and ratio floors are independent.

### Cash and selector treatments — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Refill, feasible-entrant checks, replacement hurdles and seeded exact-score tie orderings. Each row changes its named mechanism relative to the stated scoring curve.

## Frozen dataset and indicators

Load one immutable research snapshot and calculate source indicators with a single worker. Every experiment uses this same snapshot. The earlier notebook's saved results are retained as a reference; any source-reference discrepancy is reported before comparisons and investigated separately.

In [2]:
with compact_output('Frozen universe and completed features'):
    print('Loading and freezing vault universe; indicator preparation may take several minutes.')
    from repaired_data_replay import RUN_ROOT, INDICATOR_DIR, repaired_indicator_storage
    import shutil
    shutil.copy2(RUN_ROOT/"universe.pickle",ARTIFACT_DIR/"universe.pickle")
    strategy_universe,indicator_data,panel,snapshot_hash=load_snapshot(strategy,parameters,client,ARTIFACT_DIR,indicator_storage_path=INDICATOR_DIR)
    long_start=panel.dates[0].to_pydatetime()
    inputs={'repaired_inputs':json.loads((RUN_ROOT/'inputs/downloads.json').read_text()),'snapshot':snapshot_hash,'feature_panel':panel.fingerprint,'strategy':hashlib.sha256(STRATEGY_PATH.read_bytes()).hexdigest(),'guard':hashlib.sha256(GUARD_PATH.read_bytes()).hexdigest()}
    paths=[RESEARCH_DIR/'score_calibration_experiment.py',RESEARCH_DIR/'score_matrix.py',RESEARCH_DIR/'accepted_dollar_cap.py',Path('/Users/moo/code/trade-executor/tradeexecutor/strategy/alpha_model.py'),Path('/Users/moo/code/trade-executor/tradeexecutor/backtest/backtest_runner.py')]
    paths += [Path(p) for p in ['/Users/moo/code/trade-executor/tradeexecutor/backtest/backtest_pricing.py', '/Users/moo/code/trade-executor/tradeexecutor/strategy/trading_strategy_universe.py', '/Users/moo/code/trade-executor/deps/trading-strategy/tradingstrategy/alternative_data/vault.py', '/Users/moo/code/trade-executor/deps/trading-strategy/tradingstrategy/vault_permission.py']]
    inputs.update({str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths})
    fingerprint=hashlib.sha256(json.dumps(inputs,sort_keys=True).encode()).hexdigest()
    evaluator=CalibrationBacktester(strategy,strategy_universe,indicator_data,parameters,client,ExperimentPanel(panel),ARTIFACT_DIR,fingerprint,indicator_storage=repaired_indicator_storage(strategy_universe))
    present_table(pd.DataFrame([{'Vaults':panel.raw.shape[1],'Start':chart_start,'End exclusive':chart_end,'Initial equity (USD)':parameters.initial_cash,'Positions':6,'Sizing':'90-day inverse variance','Snapshot SHA-256':snapshot_hash}]),'Data and common execution settings','The same frozen snapshot, guard and execution rules supply every control and treatment. Pre-2026 observations are used only for indicators in the default replay.',CHART_PERIOD)
    present_table(pd.DataFrame([{'Input':k,'Hash':v} for k,v in inputs.items()]),'Reproducibility fingerprints','These hashes separate new engine executions from previous notebooks and prevent cache reuse across code or data changes.',CHART_PERIOD,collapsed=True)

Frozen universe and completed features — complete

### Data and common execution settings — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

The same frozen snapshot, guard and execution rules supply every control and treatment. Pre-2026 observations are used only for indicators in the default replay.

,Vaults,Start,End exclusive,Initial equity (USD),Positions,Sizing,Snapshot SHA-256
0,514,2026-01-01,2026-10-05,150000,6,90-day inverse variance,36f1b79ef89c36b99eff4c132ffcb32cac4ea447411557...

### Reproducibility fingerprints — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

These hashes separate new engine executions from previous notebooks and prevent cache reuse across code or data changes.

## Mandatory source replication

Compare the exact-formula treatment with a fresh source v11 backtest on the same data. Equity and complete trade ledgers must match before running treatments. Compare the new source metrics with the earlier saved source reference to detect a discrepancy; this comparison alone cannot identify its cause. See the root cause analysis for the subsequent input and deposit-state investigation.

In [3]:
with compact_output('Source control and formula replication'):
    source=evaluator.run_config(baseline,chart_start,chart_end,source_control=True)
    control=evaluator.run_config(baseline,chart_start,chart_end)
    def trade_ledger(run):
        return [(t.pair.pool_address,t.opened_at,t.executed_at,t.executed_quantity,t.executed_reserve,t.executed_price) for t in run['result'].state.portfolio.get_all_trades()]
    assert np.allclose(source['equity'],control['equity'],rtol=1e-10,atol=1e-6)
    assert trade_ledger(source)==trade_ledger(control),'Formula does not replicate the source trade path'
    checks=pd.DataFrame([{'Metric':k,'Source v11':source['metrics'][k],'Exact formula':control['metrics'][k],'Match':np.isclose(source['metrics'][k],control['metrics'][k],rtol=1e-10,atol=1e-6)} for k in ['Final equity (USD)','CAGR','Sharpe','Maximum drawdown','Trades']])
    assert checks.Match.all()
    present_table(checks,'Exact source replication','Fresh source and research formula must match on equity and every trade, in addition to the displayed rounded metric comparison.',CHART_PERIOD)
    old=pd.read_csv(RESEARCH_DIR/'_artifacts-matrix-long-v2'/'chart-2026-detailed-results.csv')
    old=old[old.Family.eq('Original v11')].iloc[0]
    drift=pd.DataFrame([{'Metric':k,'Earlier saved reference':old[k],'Current frozen source':source['metrics'][k],'Difference':source['metrics'][k]-old[k]} for k in ['Final equity (USD)','CAGR','Sharpe','Maximum drawdown','Trades']])
    present_table(drift,'Comparison with the saved experiment 04 source','A difference here flags failed reproduction of the earlier benchmark; metrics alone do not identify the cause. The root cause analysis traces changed historical inputs and deposit admission. Treatment improvements use the current frozen source control.',CHART_PERIOD)
    drift.to_csv(ARTIFACT_DIR/'source-reference-drift.csv',index=False)

    old_inputs=json.loads((RESEARCH_DIR/'_artifacts-matrix-long-v2'/'run-manifest.json').read_text())['inputs']
    hash_rows=[]
    for name,old_hash in old_inputs.items():
        path={'strategy':STRATEGY_PATH,'guard':GUARD_PATH,'cap_harness':RESEARCH_DIR/'accepted_dollar_cap.py','v6':Path('/Users/moo/code/strategies/strategy/hyper-ai-v6.py')}.get(name,Path(name))
        if path.is_file():hash_rows.append({'Input':name,'Unchanged since experiment 04':hashlib.sha256(path.read_bytes()).hexdigest()==old_hash})
    hash_comparison=pd.DataFrame(hash_rows)
    present_table(hash_comparison,'Recorded source and framework hash check','Compare the ten files recorded by experiment 04. This list omits raw snapshots, readers and dataset generation, so matching hashes cannot alone establish the cause of the performance difference.',CHART_PERIOD,collapsed=True)
    hash_comparison.to_csv(ARTIFACT_DIR/'reference-source-hash-comparison.csv',index=False)

Source control and formula replication — complete

### Exact source replication — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Fresh source and research formula must match on equity and every trade, in addition to the displayed rounded metric comparison.

               Metric     Source v11  Exact formula  Match
0  Final equity (USD)  194520.812686  194520.812686   True
1                CAGR       0.412004       0.412004   True
2              Sharpe       1.959590       1.959590   True
3    Maximum drawdown      -0.064031      -0.064031   True
4              Trades     581.000000     581.000000   True

### Comparison with the saved experiment 04 source — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

A difference here flags failed reproduction of the earlier benchmark; metrics alone do not identify the cause. The root cause analysis traces changed historical inputs and deposit admission. Treatment improvements use the current frozen source control.

,Metric,Earlier saved reference,Current frozen source,Difference
0,Final equity (USD),194928.639727,194520.812686,-4.078270e+02
1,CAGR,0.415920,0.412004,-3.916304e-03
2,Sharpe,1.995019,1.959590,-3.542889e-02
3,Maximum drawdown,-0.064031,-0.064031,2.505776e-08
4,Trades,582.000000,581.000000,-1.000000e+00

### Recorded source and framework hash check — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Compare the ten files recorded by experiment 04. This list omits raw snapshots, readers and dataset generation, so matching hashes cannot alone establish the cause of the performance difference.

## Controlled scoring and mechanism experiments

Run the predeclared treatments on the same frozen 2026 history. Each row is a real engine backtest, with identical initial capital and source costs. The six-position limit is asserted by the engine. Exact-score tie seeds diagnose sensitivity and are excluded from winner selection.

In [4]:
from score_calibration_report import metrics_frame, grid_figure, search_space_figure, cash_summary, saturation_audit, ic_figure, correlation_figure, quintile_figure, attribution, quarterly_figure
with compact_output('29 scoring and mechanism replays'):
    short_runs={baseline.name:control}
    for config in tqdm(score_jobs+mechanism_jobs,desc='Controlled 2026 replays'):
        short_runs[config.name]=evaluator.run_config(config,chart_start,chart_end)
    results=metrics_frame(short_runs)
    results.to_csv(ARTIFACT_DIR/'2026-results.csv',index=False)
    metric_columns=['Configuration','CAGR','Sharpe','Sortino','Maximum drawdown','Mean cash weight','Trades','Modelled redemption costs (USD)']
    primary=results[~results.name.str.startswith('Tie seed')].sort_values('CAGR',ascending=False)
    best_name=primary.iloc[0].Configuration
    best_sharpe_name=primary.sort_values('Sharpe',ascending=False).iloc[0].Configuration
    present_table(metric_table(primary[metric_columns].reset_index(drop=True),'Net performance by controlled treatment'),'Key metrics side by side','Sorted by observed CAGR. All 18 scoring and six cash/selector treatments are shown; seeded tie diagnostics are presented separately. Green indicates a stronger value within each metric column, not independent statistical significance.',CHART_PERIOD)
    chart_intro('Independent clipping grid','Each cell changes only the two upper clips. Coefficients stay 60% CAGR / 40% Sortino; risk history is 45 days, position sizing is 90-day inverse variance, and selection is the original source machinery.',CHART_PERIOD)
    show_static(grid_figure(results),CHART_PERIOD)

    chart_intro('Risk and return clusters','CAGR/Sharpe, CAGR/drawdown and Sharpe/drawdown panels group treatments by mechanism. The black star is the exact source control; open grey circles are tie probes. Higher is better on each metric axis, including less-negative drawdown. Overlapping points can represent identical trading paths.',CHART_PERIOD)
    show_static(search_space_figure(results),CHART_PERIOD)

29 scoring and mechanism replays — complete

### Key metrics side by side — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Sorted by observed CAGR. All 18 scoring and six cash/selector treatments are shown; seeded tie diagnostics are presented separately. Green indicates a stronger value within each metric column, not independent statistical significance.

### Independent clipping grid — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Each cell changes only the two upper clips. Coefficients stay 60% CAGR / 40% Sortino; risk history is 45 days, position sizing is 90-day inverse variance, and selection is the original source machinery.

### Risk and return clusters — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

CAGR/Sharpe, CAGR/drawdown and Sharpe/drawdown panels group treatments by mechanism. The black star is the exact source control; open grey circles are tie probes. Higher is better on each metric axis, including less-negative drawdown. Overlapping points can represent identical trading paths.

## Cash usage and selection diagnostics

Separate intended dollar recovery from realised exposure. Refill redistributes residual fresh budget only among the same selected eligible vaults, after deposit checks, under the original concentration and TVL limits. It keeps the ordinary execution thresholds and never adds a seventh holding.

In [5]:
cash=cash_summary(short_runs)
cash.to_csv(ARTIFACT_DIR/'2026-cash-diagnostics.csv',index=False)
comparison_names=['Hard C1 S3','Blend 46d','Smooth C1 S3','Hard C1 S3 / refill','Blend 46d / refill','Smooth C1 S3 / refill']
paired=results.set_index('Configuration').loc[comparison_names].reset_index()
present_table(metric_table(paired[metric_columns],'Scoring × cash comparison'),'Scoring and cash comparison','Matched scoring curves with and without refill. Blend 45d and Legacy 46d in the main table isolate the one-day risk-window change from the blended scoring curve.',CHART_PERIOD)
cash_view=cash.set_index('Configuration').loc[comparison_names].reset_index()
percent_cash=[c for c in cash_view if ' / budget' in c or c=='Mean cash weight']
present_table(cash_view.style.format({c:'{:.2%}' for c in percent_cash}).background_gradient(subset=percent_cash,cmap='Blues'),'Target recovery and realised cash','Fractions use the fresh investable budget on decisions with positive budget. Blocked top-ups explain one source of residual cash; concentration limits and execution bands explain others. Recovered targets need not become filled exposure.',CHART_PERIOD)
selector_names=['Hard C1 S3','Feasible entrants','Replacement hurdle 0.025','Replacement hurdle 0.05']
present_table(metric_table(results.set_index('Configuration').loc[selector_names,metric_columns[1:]].reset_index(),'Selector interventions'),'Feasible entrants and replacement hurdles','Feasible-entry checks prevent an unavailable entrant from supplying the displacement score. Hurdles then require a 0.025 or 0.05 composite-score advantage. Other source entry/exit and capacity rules are preserved.',CHART_PERIOD)
tie_names=['Hard C1 S3']+[c.name for c in mechanism_jobs if c.tie_seed]
present_table(metric_table(results.set_index('Configuration').loc[tie_names,metric_columns[1:]].reset_index(),'Exact-score tie sensitivity'),'Address-order tie sensitivity','Alternative deterministic seeded address orderings affect only exactly equal scores. These rows quantify arbitrary tie sensitivity and are not eligible winners.',CHART_PERIOD)
saturation,ties=saturation_audit(panel,control,chart_start,chart_end)
saturation.to_csv(ARTIFACT_DIR/'2026-saturation.csv',index=False)
present_table(saturation.style.format({'At or above cap':'{:.1%}','Zero or negative':'{:.1%}','Median raw metric':'{:.3f}'}),'Where the clips saturate','Compare all finite vault-days with observations actually funded by the fixed original-formula control. Drawdown uses absolute magnitude for its adverse tail; other metrics use their upper tail. This audits thresholds without selecting profitable vaults afterwards.',CHART_PERIOD,collapsed=False)
present_table(pd.DataFrame([ties]).style.format({'Maximum score fraction':'{:.1%}','Dates with at least two funded maximum-score vaults':'{:.1%}'}),'Maximum-score ties in funded positions','Composite score 1 means both original components saturate. Repeated ties erase ranking distinctions and make address-order sensitivity relevant.',CHART_PERIOD)

### Scoring and cash comparison — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Matched scoring curves with and without refill. Blend 45d and Legacy 46d in the main table isolate the one-day risk-window change from the blended scoring curve.

### Target recovery and realised cash — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Fractions use the fresh investable budget on decisions with positive budget. Blocked top-ups explain one source of residual cash; concentration limits and execution bands explain others. Recovered targets need not become filled exposure.

### Feasible entrants and replacement hurdles — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Feasible-entry checks prevent an unavailable entrant from supplying the displacement score. Hurdles then require a 0.025 or 0.05 composite-score advantage. Other source entry/exit and capacity rules are preserved.

### Address-order tie sensitivity — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Alternative deterministic seeded address orderings affect only exactly equal scores. These rows quantify arbitrary tie sensitivity and are not eligible winners.

### Where the clips saturate — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Compare all finite vault-days with observations actually funded by the fixed original-formula control. Drawdown uses absolute magnitude for its adverse tail; other metrics use their upper tail. This audits thresholds without selecting profitable vaults afterwards.

### Maximum-score ties in funded positions — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Composite score 1 means both original components saturate. Repeated ties erase ranking distinctions and make address-order sensitivity relevant.

## Causal feature diagnostics

Features use completed data at T−1; labels cover the next 14, 30 or 60 daily NAV returns. Both raw forward return and forward realised Sharpe are analysed. Future labels are censored at the report end. Every decision date receives equal weight, reducing domination by dates with larger universes. These are gross NAV associations rather than executable portfolio returns.

The source inclusion, return gate, quarantine and recorded whitelist define this diagnostic universe. Individual state exclusions and deposit availability can further restrict trading. Overlapping labels, carried NAV and current archive membership remain limitations. The diagnostics do not feed back into parameters for this run.

In [6]:
from score_calibration_experiment import ic_summary
with compact_output('Forward feature diagnostics'):
    audit_dir=ARTIFACT_DIR/('features-'+fingerprint[:16])
    audit_dir.mkdir(exist_ok=True)
    labels=['ic','bins','correlations','coverage']
    if all((audit_dir/(label+'.csv')).exists() for label in labels):
        ic,bins,correlations,coverage=[pd.read_csv(audit_dir/(label+'.csv'),parse_dates=['Date']) for label in labels]
    else:
        ic,bins,correlations,coverage=feature_audit(strategy,strategy_universe,indicator_data,panel,parameters,chart_start,chart_end)
        for label,frame in zip(labels,[ic,bins,correlations,coverage]):frame.to_csv(audit_dir/(label+'.csv'),index=False)
    feature_summary=ic_summary(ic)
    feature_summary.to_csv(ARTIFACT_DIR/'2026-forward-feature-summary.csv',index=False)
    for outcome in ['Forward return','Forward Sharpe']:
        view=feature_summary[(feature_summary.Outcome==outcome)&feature_summary.Horizon.eq(30)].sort_values('Mean IC',ascending=False).head(12)
        present_table(view.drop(columns=['Outcome','Horizon']).style.format({'Mean IC':'{:+.3f}','Positive IC fraction':'{:.1%}','Mean paired vaults':'{:.1f}','Lower block band':'{:+.3f}','Upper block band':'{:+.3f}'}).background_gradient(subset=['Mean IC'],cmap='RdBu',vmin=-1,vmax=1),'Highest 30-day associations: '+outcome.lower(),'Equal-date mean cross-sectional Spearman IC. Positive means larger historical feature values rank stronger future outcomes. Exploratory 200-draw moving-block bands preserve some overlapping-label dependence; the table is descriptive, not a feature selection rule.',CHART_PERIOD)
        chart_intro('Forward associations: '+outcome.lower(),'Heatmap cells show equal-date mean cross-sectional IC, on a shared −1 to +1 scale. Missing cells lack enough variable, paired observations. Drawdown is stored as a negative return: a larger value means a smaller historical loss.',CHART_PERIOD)
        show_static(ic_figure(feature_summary,outcome),CHART_PERIOD)
    chart_intro('Feature redundancy including Sortino','Average per-date Spearman correlations among eligible candidates. The separate 45-, 90- and 360-day panels show whether alternative metrics duplicate the original inputs. Pairwise missing-value deletion is used; correlations are not predictive IC.',CHART_PERIOD)
    show_static(correlation_figure(correlations),CHART_PERIOD)
    chart_intro('Monotonic feature bins','Average next-30-day NAV returns for within-date feature-rank quintiles. Each date contributes equally within its populated bins; ties can leave bins empty. The highest quintile should improve consistently before a feature is trusted as a ranker.',CHART_PERIOD)
    show_static(quintile_figure(bins),CHART_PERIOD)
    cover=coverage.groupby(['Period','Metric'])[['Eligible vaults','Finite feature']].sum()
    cover['Finite coverage']=cover['Finite feature']/cover['Eligible vaults']
    cover=cover.reset_index()
    present_table(cover.style.format({'Finite coverage':'{:.1%}'}),'Feature coverage among eligible candidates','Denominator is the gate-filtered diagnostic universe on 2026 decision dates, rather than all vault/calendar observations. Undefined ratios and missing history remain separate from zero scores. Young vaults retain the treatment-specific missing policy.',CHART_PERIOD,collapsed=True)

Forward feature diagnostics — complete

### Highest 30-day associations: forward return — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Equal-date mean cross-sectional Spearman IC. Positive means larger historical feature values rank stronger future outcomes. Exploratory 200-draw moving-block bands preserve some overlapping-label dependence; the table is descriptive, not a feature selection rule.

### Forward associations: forward return — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Heatmap cells show equal-date mean cross-sectional IC, on a shared −1 to +1 scale. Missing cells lack enough variable, paired observations. Drawdown is stored as a negative return: a larger value means a smaller historical loss.

### Highest 30-day associations: forward sharpe — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Equal-date mean cross-sectional Spearman IC. Positive means larger historical feature values rank stronger future outcomes. Exploratory 200-draw moving-block bands preserve some overlapping-label dependence; the table is descriptive, not a feature selection rule.

### Forward associations: forward sharpe — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Heatmap cells show equal-date mean cross-sectional IC, on a shared −1 to +1 scale. Missing cells lack enough variable, paired observations. Drawdown is stored as a negative return: a larger value means a smaller historical loss.

### Feature redundancy including Sortino — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Average per-date Spearman correlations among eligible candidates. The separate 45-, 90- and 360-day panels show whether alternative metrics duplicate the original inputs. Pairwise missing-value deletion is used; correlations are not predictive IC.

### Monotonic feature bins — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Average next-30-day NAV returns for within-date feature-rank quintiles. Each date contributes equally within its populated bins; ties can leave bins empty. The highest quintile should improve consistently before a feature is trusted as a ranker.

### Feature coverage among eligible candidates — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Denominator is the gate-filtered diagnostic universe on 2026 decision dates, rather than all vault/calendar observations. Undefined ratios and missing history remain separate from zero scores. Young vaults retain the treatment-specific missing policy.

## Predeclared full-history confirmations

Run the six predeclared controls and treatments over all available vault history, starting March 2023. These overlap the default 2026 comparison and are sensitivity checks, not an independent holdout. Detailed full-history metrics are saved separately in the ignored artefact directory; all displayed performance tables and charts continue to use 2026.

In [7]:
with compact_output('Six full-history confirmations'):
    long_runs={}
    for config in tqdm(long_jobs,desc='Full-history confirmations'):
        long_runs[config.name]=evaluator.run_config(config,long_start,chart_end)
    long_results=metrics_frame(long_runs)
    long_results.to_csv(ARTIFACT_DIR/'long-results.csv',index=False)
    long_source=evaluator.run_config(baseline,long_start,chart_end,source_control=True)
    assert np.allclose(long_source['equity'],long_runs[baseline.name]['equity'],rtol=1e-10,atol=1e-6)
    assert trade_ledger(long_source)==trade_ledger(long_runs[baseline.name])
    manifest={'inputs':inputs,'fingerprint':fingerprint,'default_start':str(chart_start),'end_exclusive':str(chart_end),'full_history_start':str(long_start),'scoring':[c.__dict__ for c in score_jobs],'mechanisms':[c.__dict__ for c in mechanism_jobs],'confirmations':[c.__dict__ for c in long_jobs],'executions':evaluator.records,'source_replication_2026':True,'source_replication_full_history':True}
    (ARTIFACT_DIR/'run-manifest.json').write_text(json.dumps(manifest,indent=2))

Six full-history confirmations — complete

## Portfolio paths and allocations

Show the six predeclared scoring/cash paths over 2026. The default comparison has fresh initial holdings in January; it is not the 2026 slice of an already-running multi-year portfolio.

In [8]:
import plotly.graph_objects as go
from tradeexecutor.strategy.chart.definition import ChartInput
from tradeexecutor.strategy.chart.standard.weight import equity_curve_by_asset
from score_matrix_visualisation import allocation_colours, style_allocation
path_runs={name:short_runs[name] for name in comparison_names}
fig=go.Figure()
for name,run in path_runs.items():fig.add_trace(go.Scatter(x=run['equity'].index,y=run['equity'].values,name=name,mode='lines'))
fig.update_layout(title='Predeclared scoring and cash equity paths',width=1500,height=700,template='plotly_white',yaxis=dict(title='Equity (USD)',tickprefix='$'),xaxis_title='Date',legend=dict(orientation='h',y=-.2),margin=dict(t=110,b=150))
chart_intro('Matched equity curves','Six predeclared scoring/cash paths start at $150,000 on the same frozen archive. Compare timing and drawdowns as well as final capital; the retrospective winners are shown separately in allocations.',CHART_PERIOD)
show_static(fig,CHART_PERIOD)
chart_intro('Quarterly profit heatmap','Compounded portfolio returns for the same six predeclared paths. Colours use one zero-centred scale. Q4 is partial, ending at the report boundary; these quarters were already observed and are not validation folds.',CHART_PERIOD)
show_static(quarterly_figure(path_runs),CHART_PERIOD)
allocation_names=list(dict.fromkeys([baseline.name,best_name,best_sharpe_name]))
allocation_figures=[]
for name in allocation_names:
    run=short_runs[name]
    fig=equity_curve_by_asset(ChartInput(execution_context=notebook_execution_context,state=run['result'].state,pairs=[],backtest_start_at=chart_start,backtest_end_at=chart_end))
    fig.update_layout(title='Absolute asset allocation — '+name,width=1500,height=max(900,170+20*len(fig.data)))
    allocation_figures.append((name,fig))
colours=allocation_colours([fig for _,fig in allocation_figures])
ceiling=max(short_runs[name]['equity'].max() for name in allocation_names)*1.05
for name,fig in allocation_figures:
    chart_intro('Absolute allocation: '+name,'Stacked marked USD holdings, including grey reserve cash, use the existing trade-executor chart. The top edge is portfolio equity; this is not percentage weighting. Vault colours and USD bounds are shared. The baseline and retrospectively strongest CAGR/Sharpe paths are displayed.',CHART_PERIOD)
    style_allocation(fig,colours,ceiling)
    show_static(fig,CHART_PERIOD)

### Matched equity curves — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Six predeclared scoring/cash paths start at $150,000 on the same frozen archive. Compare timing and drawdowns as well as final capital; the retrospective winners are shown separately in allocations.

### Quarterly profit heatmap — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Compounded portfolio returns for the same six predeclared paths. Colours use one zero-centred scale. Q4 is partial, ending at the report boundary; these quarters were already observed and are not validation folds.

### Absolute allocation: Hard C1 S3 — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Stacked marked USD holdings, including grey reserve cash, use the existing trade-executor chart. The top edge is portfolio equity; this is not percentage weighting. Vault colours and USD bounds are shared. The baseline and retrospectively strongest CAGR/Sharpe paths are displayed.

### Absolute allocation: Feasible entrants — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Stacked marked USD holdings, including grey reserve cash, use the existing trade-executor chart. The top edge is portfolio equity; this is not percentage weighting. Vault colours and USD bounds are shared. The baseline and retrospectively strongest CAGR/Sharpe paths are displayed.

### Absolute allocation: Blend 46d — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Stacked marked USD holdings, including grey reserve cash, use the existing trade-executor chart. The top edge is portfolio equity; this is not percentage weighting. Vault colours and USD bounds are shared. The baseline and retrospectively strongest CAGR/Sharpe paths are displayed.

## Profit attribution and jump analysis

Reconcile every position's PnL to marked equity, then inspect profit concentration, best days, kurtosis and individual positions. Removing a vault's PnL or zeroing the best day retains the original trading path; these are sensitivities rather than new backtests. Curator annotations describe current research quality flags, and BTC/ETH comparisons use matching valuation intervals.

In [9]:
from tradingstrategy.binance.price import fetch_binance_price
with compact_output('Position and market attribution'):
    market={symbol:fetch_binance_price(symbol=symbol+'USDT',start=chart_start-datetime.timedelta(days=7))['open'] for symbol in ['BTC','ETH']}
    robustness,contributors,jumps,positions=attribution(short_runs,market)
    for label,frame in [('robustness',robustness),('contributors',contributors),('jumps',jumps),('positions',positions)]:frame.to_csv(ARTIFACT_DIR/('2026-'+label+'.csv'),index=False)
    inspection_names=list(dict.fromkeys([baseline.name,best_name,best_sharpe_name]+comparison_names))
    view=robustness[robustness.Configuration.isin(inspection_names)]
    present_table(view.style.format({'Best day return':'{:.2%}','Leader share of positive vault PnL':'{:.1%}','Excess kurtosis':'{:.2f}','Sharpe with best day zeroed':'{:.2f}','Sharpe without leader (fixed ledger)':'{:.2f}','CAGR without leader (fixed ledger)':'{:.2%}','Leading vault profit (USD)':'${:,.0f}','Attribution residual (USD)':'{:.2e}'}),'Concentration and best-day sensitivity','Predeclared paths plus the strongest observed CAGR and Sharpe treatments. Leader share uses positive vault PnL, so losses do not inflate its denominator. A strong headline result needs several independent contributors and stability after exceptional-day removal.',CHART_PERIOD)
    present_table(contributors[contributors.Configuration.isin(inspection_names)],'Largest contributing vaults','Top five vault profit contributors per displayed path, with curator quality and exclusion annotations. Unrated is a missing quality annotation, not evidence of reliability.',CHART_PERIOD,collapsed=True)
    present_table(jumps[jumps.Configuration.isin(inspection_names)],'Largest equity jumps and market context','Top three positive daily portfolio returns per displayed path. BTC and ETH use cached Binance open prices across the corresponding valuation interval; large vault-led jumps without comparable market movement merit scrutiny.',CHART_PERIOD,collapsed=True)
    present_table(positions[positions.Configuration.isin(inspection_names)],'Largest individual positions','Top three profitable position lifecycles per displayed path. The profit curves include modelled costs and reconcile to the portfolio; multiple positions can belong to the same vault.',CHART_PERIOD,collapsed=True)
    assert results['Maximum vaults held'].le(6).all()
    assert long_results['Maximum vaults held'].le(6).all()
    (ARTIFACT_DIR/'completed.json').write_text(json.dumps({'fingerprint':fingerprint,'short_runs':len(short_runs),'long_runs':len(long_runs),'best_CAGR':best_name,'best_Sharpe':best_sharpe_name,'source_replication':True,'attribution_max_residual':robustness['Attribution residual (USD)'].max(),'ties':ties},indent=2))

Position and market attribution — complete

### Concentration and best-day sensitivity — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Predeclared paths plus the strongest observed CAGR and Sharpe treatments. Leader share uses positive vault PnL, so losses do not inflate its denominator. A strong headline result needs several independent contributors and stability after exceptional-day removal.

### Largest contributing vaults — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Top five vault profit contributors per displayed path, with curator quality and exclusion annotations. Unrated is a missing quality annotation, not evidence of reliability.

### Largest equity jumps and market context — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Top three positive daily portfolio returns per displayed path. BTC and ETH use cached Binance open prices across the corresponding valuation interval; large vault-led jumps without comparable market movement merit scrutiny.

### Largest individual positions — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Top three profitable position lifecycles per displayed path. The profit curves include modelled costs and reconcile to the portfolio; multiple positions can belong to the same vault.