# Experiment 06 — three and four scoring inputs

Based on [04-opt-score-matrix.ipynb](04-opt-score-matrix.ipynb) and [05-opt-score-calibration-selection-cash.ipynb](05-opt-score-calibration-selection-cash.ipynb).

## User goal

Test scoring systems with **three and four distinct inputs**, rather than inferring from the two-input winners that more complex scores cannot improve the strategy. An input is one metric/lookback cell, not a clipping term or a position weight.

## Method

Use the fixed 7 October publication and unchanged v11 universe, selection, guards, costs, two-day cadence, six positions and 90-day inverse-variance sizing. Keep the original unscored/missing behaviour and the parent capacity redistribution. Compare original 360-day CAGR/45-day Sortino scoring and the 360/46-day clipping blend.

Predeclare 18 supports per cardinality and clipping family: **36 three-input and 36 four-input configurations**, plus two two-input controls. For three inputs, allocate 48% to 360-day CAGR, 32% to core Sortino and 20% to one additional feature. For four inputs, keep the same core and allocate 10% to each of two additional features. This holds the total added mass at 20%, preventing negligible extra weights from masquerading as meaningful complexity. Additional cells span CAGR, Sharpe, Sortino, maximum drawdown and Calmar across short and long windows.

Run every configuration on both **2026-01-01 → 2026-10-05** and **2023-03-01 → 2026-10-05**, end exclusive, UTC, with fresh $150,000 starts. All feature observations precede decisions. Additional unavailable metrics propagate an unscored composite; young vaults are not automatically excluded. These periods overlap, so neither is an independent holdout. The initial grid does not optimise coefficients or exhaust all possible supports. Report full-history-selected candidates separately from descriptive 2026 maxima.

## Presentation

Default charts and tables use the 2026 period. Full-history evidence is collapsed and retained in ignored artefacts. Every displayed table and chart has a subheading, description and explicit period. Source/exact-formula controls must agree on full equity and trade ledgers. Examine best-day jumps, leading vaults, curator annotations and BTC/ETH intervals before interpreting a high CAGR as broadly supported.

## Key new insights

- **3 inputs, highest 2026 CAGR:** Blend 46d / 3 inputs / 6m CAGR: 51.99% CAGR, 2.29 Sharpe and -7.29% drawdown. Highest Sharpe is 2.29 for Blend 46d / 3 inputs / 6m CAGR.
- **4 inputs, highest 2026 CAGR:** Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR: 52.30% CAGR, 2.23 Sharpe and -7.62% drawdown. Highest Sharpe is 2.30 for Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino.
- **Joint improvements against original v11:** 1 of 72 added-input configurations have higher 2026 CAGR and Sharpe with no worse drawdown. This does not establish unseen-time improvement.

- **Strongest balanced four-input candidate:** 48% 360-day CAGR + 32% 45-day Sortino + 10% 180-day CAGR + 10% 30-day Sortino, with legacy score clips (CAGR 100%, Sortino 3). It improves 2026 CAGR and Sharpe with slightly better drawdown than original v11; full-history drawdown is slightly worse (-8.08% versus -7.92%). These are four metric/window inputs but only two different metrics.
- **Extra windows matter in this replay:** collapsing the four-input leader to the same 58/42 metric balance on just 360-day CAGR/45-day Sortino reduces 2026 CAGR from 51.77% to 41.89% and Sharpe from 2.30 to 1.99. Full-history CAGR falls from 22.05% to 15.85% and Sharpe from 1.62 to 1.24. This diagnostic supports an incremental benefit from the additional windows, subject to search selection bias.

## Summary of results

### Selected comparisons — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Two-input controls, the best full-history candidates at each cardinality/objective, and the descriptive 2026 maxima. Every candidate uses six inverse-variance positions and unchanged selection. Equivalent paths can repeat.

| Configuration | Inputs | CAGR | Sharpe | Maximum drawdown | Mean cash weight | Trades |
| --- | --- | --- | --- | --- | --- | --- |
| Legacy 45d | 2 | 41.20% | 1.96 | -6.40% | 8.83% | 581 |
| Blend 46d | 2 | 41.38% | 2.12 | -4.85% | 7.43% | 583 |
| Blend 46d / 3 inputs / 1m Sortino | 3 | 39.26% | 2.05 | -4.93% | 6.87% | 647 |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 4 | 51.77% | 2.30 | -6.35% | 10.18% | 569 |
| Blend 46d / 3 inputs / 6m CAGR | 3 | 51.99% | 2.29 | -7.29% | 9.80% | 569 |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 4 | 52.30% | 2.23 | -7.62% | 8.41% | 593 |

<details><summary>Same configurations over full history — 2023-03-01 → 2026-10-05 (end exclusive, UTC)</summary>

Independent $150,000 starts; this period overlaps 2026 and is not a holdout.

| Configuration | Inputs | CAGR | Sharpe | Maximum drawdown | Mean cash weight | Trades |
| --- | --- | --- | --- | --- | --- | --- |
| Legacy 45d | 2 | 15.77% | 1.24 | -7.92% | 41.81% | 1074 |
| Blend 46d | 2 | 15.42% | 1.24 | -8.51% | 41.18% | 1060 |
| Blend 46d / 3 inputs / 1m Sortino | 3 | 17.45% | 1.31 | -9.50% | 42.52% | 1158 |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 4 | 22.05% | 1.62 | -8.08% | 43.71% | 1071 |
| Blend 46d / 3 inputs / 6m CAGR | 3 | 17.15% | 1.30 | -7.92% | 41.67% | 1063 |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 4 | 19.57% | 1.45 | -7.92% | 41.77% | 1088 |

</details>

## Robustness of results

All 74 configurations completed both periods. Three-input scores allocate 20% to one additional metric/window; four-input scores allocate 10% to each of two additional cells. Both keep 80% on the same 60/40 CAGR/Sortino core. This tests a predeclared add-on grid, not all combinations or optimal coefficients. Missing additional metrics propagate an unscored composite, as in the source; sparse long-window coverage can therefore change ranking materially. Full-history selections and 2026 maxima are labelled separately, with no claim of independent validation.

Source v11 and its exact two-input matrix match equity and complete trade ledgers in both periods. Position attribution reconciles to initial capital with a maximum residual of 5.82e-11 USD. The notebook reports best days, excess kurtosis, leading-vault concentration, curator annotations and matching BTC/ETH intervals. Fixed-ledger contributor removals are sensitivities, not executable exclusion backtests.

## Setup and predeclared design

Load the pinned restored inputs and define the candidate supports before looking at their portfolio returns.

In [1]:
from pathlib import Path
import sys
RESEARCH_DIR = Path('/Users/moo/code/getting-started/scratchpad/hyperliquid-vov-2nd')
sys.path.insert(0, str(RESEARCH_DIR))
from score_matrix_visualisation import compact_output, chart_intro, present_table, metric_table, show_static, style_allocation, allocation_colours
with compact_output('Pinned inputs and candidate design'):
    import json
    import numpy as np
    import pandas as pd
    import plotly.express as px
    from tradeexecutor.utils.notebook import setup_charting_and_output, OutputMode
    from score_input_count_experiment import *
    from score_calibration_report import attribution, quarterly_figure
    setup_charting_and_output(OutputMode.static, image_format='png', width=1500, height=900)
    evaluator, parameters, candidates, cache_path = initialise()
    lookup = {row['Configuration']: row for row in candidates}
    assert parameters.max_assets_in_portfolio == 6 and parameters.inverse_vol_window == 90
    design = pd.DataFrame([{k:v for k,v in row.items() if k not in ('Weights','Profile')} for row in candidates])
present_table(design.groupby(['Family','Inputs']).size().rename('Configurations').reset_index(),
              'Predeclared candidate counts', 'Two clipping families; exactly 18 supports for each three/four-input arm. Position sizing and selection remain fixed.', SHORT_PERIOD)
present_table(design, 'All input supports', 'The exact additional feature identities, listed before execution. Both cardinalities assign a total of 20% to additional features.', SHORT_PERIOD, collapsed=True)

Pinned inputs and candidate design — complete

### Predeclared candidate counts — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Two clipping families; exactly 18 supports for each three/four-input arm. Position sizing and selection remain fixed.

       Family  Inputs  Configurations
0   Blend 46d       2               1
1   Blend 46d       3              18
2   Blend 46d       4              18
3  Legacy 45d       2               1
4  Legacy 45d       3              18
5  Legacy 45d       4              18

### All input supports — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

The exact additional feature identities, listed before execution. Both cardinalities assign a total of 20% to additional features.

## Source replication

Check that the two-input wrapper expresses the original strategy before adding inputs.

In [2]:
control_runs = {}
replication = []
def trade_ledger(run):
    return [(t.pair.pool_address,t.opened_at,t.executed_at,t.executed_quantity,t.executed_reserve,t.executed_price) for t in run['result'].state.portfolio.get_all_trades()]
with compact_output('Source and two-input controls'):
    for period in PERIODS:
        row = lookup['Legacy 45d']
        source = evaluator.run(row['Weights'], *PERIODS[period], n=6, sizing='inverse_variance', missing=True, profile='legacy', source_control=True, keep=True)
        exact = evaluate(evaluator, row, period, keep=True)
        assert np.allclose(source['equity'], exact['equity'], rtol=0, atol=1e-6)
        assert trade_ledger(source) == trade_ledger(exact)
        control_runs[period] = source
        replication.append({'Period':period,'Final equity (USD)':source['metrics']['Final equity (USD)'],'Trades':source['metrics']['Trades'],'Full equity and ledger match':True})
    saved = json.loads((RUN_ROOT/'01/metrics.json').read_text())
    for period, old_name in [('2026','Short (source reference)'),('Long','Long (all available vault history)')]:
        for metric in ('Final equity (USD)','CAGR','Sharpe','Maximum drawdown','Trades'):
            assert np.isclose(control_runs[period]['metrics'][metric], saved[old_name][metric], rtol=1e-12, atol=1e-8)
present_table(pd.DataFrame(replication).query("Period == '2026'"), 'Original v11 replication', 'The exact two-input wrapper matches every source trade and the complete equity path. The same checks pass over full history.', SHORT_PERIOD)
(pd.DataFrame(replication)).to_csv(ARTIFACT_DIR/'replication.csv',index=False)

Source and two-input controls — complete

### Original v11 replication — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

The exact two-input wrapper matches every source trade and the complete equity path. The same checks pass over full history.

  Period  Final equity (USD)  Trades  Full equity and ledger match
1   2026       194520.812686     581                          True

## Both backtesting periods

Evaluate every predeclared candidate. These are bounded comparisons of feature additions, with unchanged coefficient mass, position sizing and selection.

In [3]:
with compact_output('Full-history input grid'):
    long_results = run_grid(evaluator, candidates, 'Long')
with compact_output('2026 input grid'):
    short_results = run_grid(evaluator, candidates, '2026')
assert len(short_results) == len(long_results) == 74
columns = ['Family','Inputs','Added inputs','CAGR','Sharpe','Maximum drawdown','Mean cash weight','Trades']
present_table(metric_table(short_results[columns].sort_values('CAGR',ascending=False), f'All 74 scoring configurations — {SHORT_PERIOD}'), 'Complete scoring comparison', 'Original two-input controls and all three/four-input candidates on identical inputs. Green denotes a higher metric or less negative drawdown; no new settings are selected by this display.', SHORT_PERIOD, collapsed=True)
present_table(metric_table(long_results[columns], f'Full-history scoring comparison — {LONG_PERIOD}'), 'Full-history evidence', 'Every same configuration has an independent fresh-start full-history backtest. The periods overlap and are not holdouts.', LONG_PERIOD, collapsed=True)

Full-history input grid — complete

2026 input grid — complete

### Complete scoring comparison — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Original two-input controls and all three/four-input candidates on identical inputs. Green denotes a higher metric or less negative drawdown; no new settings are selected by this display.

### Full-history evidence — 2023-03-01 → 2026-10-05 (end exclusive, UTC)

Every same configuration has an independent fresh-start full-history backtest. The periods overlap and are not holdouts.

## Candidate comparisons

Separate the best configurations selected on full history from the highest observed results in 2026.

In [4]:
selection_rows = []
for selection_period, frame in [('Full history',long_results),('2026 descriptive',short_results)]:
    for count in (3,4):
        subset = frame[frame.Inputs.eq(count)]
        for objective in ('CAGR','Sharpe'):
            best = subset.sort_values([objective,'Configuration'],ascending=[False,True]).iloc[0]
            observed = short_results[short_results.Configuration.eq(best.Configuration)].iloc[0]
            selection_rows.append({'Selected on':selection_period,'Objective':objective,**observed.to_dict()})
selected_names = shortlist(short_results,long_results)
selected_short = short_results[short_results.Configuration.isin(selected_names)]
present_table(metric_table(pd.DataFrame(selection_rows)[['Selected on','Objective',*columns]], f'Chosen supports replayed in 2026 — {SHORT_PERIOD}'), 'Selection provenance and 2026 performance', 'Each row identifies the period used to pick its support. All performance columns are 2026 replays; full-history selection still overlaps this window.', SHORT_PERIOD)
coefficients = support_table(candidates, selected_names)
present_table(coefficients.style.format({'Weight':'{:.0%}'}).background_gradient(subset=['Weight'],cmap='Blues'), 'Exact coefficients of retained candidates', 'Each input is a distinct metric/lookback. Clipping recipes can have multiple nonlinear terms for one input, without increasing the feature count.', SHORT_PERIOD, collapsed=True)
coefficients.to_csv(ARTIFACT_DIR/'selected-coefficients.csv',index=False)
(pd.DataFrame(selection_rows)).to_csv(ARTIFACT_DIR/'selection-provenance.csv',index=False)

### Selection provenance and 2026 performance — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Each row identifies the period used to pick its support. All performance columns are 2026 replays; full-history selection still overlaps this window.

### Exact coefficients of retained candidates — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Each input is a distinct metric/lookback. Clipping recipes can have multiple nonlinear terms for one input, without increasing the feature count.

## Search-space charts

Compare input identities, complexity and clipping families. All charts below use the 2026 window.

In [5]:
for count in (3,4):
    chart_intro(f'Exactly {count} scoring inputs', 'Each row is a predeclared support. The legacy and clipping-blend families share fixed sizing and the same added-input mass. Read the metric columns together to assess return/risk trade-offs.', SHORT_PERIOD)
    show_static(grid_figure(short_results,count), SHORT_PERIOD)
chart_intro('Return versus Sharpe by input count', 'Every point is an actual backtest, coloured by the number of feature inputs and shaped by the clipping family. Two-input controls provide the reference; this is an exploratory parameter map.', SHORT_PERIOD)
scatter = scatter_figure(short_results)
scatter.update_layout(legend=dict(orientation='h', x=0, y=1.08, title='Clipping family'),
                      coloraxis_colorbar=dict(title='Inputs', tickvals=[2,3,4], x=1.02),
                      margin=dict(t=140, r=120))
show_static(scatter, SHORT_PERIOD)

### Exactly 3 scoring inputs — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Each row is a predeclared support. The legacy and clipping-blend families share fixed sizing and the same added-input mass. Read the metric columns together to assess return/risk trade-offs.

### Exactly 4 scoring inputs — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Each row is a predeclared support. The legacy and clipping-blend families share fixed sizing and the same added-input mass. Read the metric columns together to assess return/risk trade-offs.

### Return versus Sharpe by input count — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Every point is an actual backtest, coloured by the number of feature inputs and shaped by the clipping family. Two-input controls provide the reference; this is an exploratory parameter map.

## Equity, quarterly returns and allocation

Retain states for the two-input controls and the full-history/2026 leaders, so numerical results can be checked against the trading paths.

In [6]:
with compact_output('Retained candidate states'):
    retained = {name:evaluate(evaluator,lookup[name],'2026',keep=True) for name in selected_names}
    print(f'Retained {len(retained)} paths; cached engine metrics are checked when states are loaded or rerun.')
    for name,run in retained.items():
        stored = short_results[short_results.Configuration.eq(name)].iloc[0]
        for metric,value in run['metrics'].items():
            assert np.isclose(value,stored[metric],rtol=1e-12,atol=1e-8)
def label(name):
    row=lookup[name]
    return name if row['Inputs']==2 else f"{row['Family']} · {row['Inputs']} inputs · support {row['Support']:02d}"
chart_runs = {label(name):run for name,run in retained.items()}
equity_frame = pd.DataFrame({name:run['equity'] for name,run in chart_runs.items()})
equity_frame.index.name = 'Date'
chart_intro('Equity paths of retained supports', 'Labels identify the clipping family, input count and support number; full coefficients are listed above. All start with $150,000 and no inherited positions.', SHORT_PERIOD)
show_static(px.line(equity_frame, title='Equity of two, three and four-input score candidates', width=1600,height=650,template='plotly_white', labels={'value':'Portfolio equity (USD)','Date':'Date','variable':'Configuration'}), SHORT_PERIOD)
chart_intro('Quarterly profit and loss', 'Compounded daily portfolio returns on a common colour scale. The final quarter is partial.', SHORT_PERIOD)
show_static(quarterly_figure(chart_runs), SHORT_PERIOD)
from tradeexecutor.analysis.weights import calculate_asset_weights, visualise_weights
from tradeexecutor.strategy.chart.renderer import ChartBacktestRenderingSetup
from tradeexecutor.strategy.execution_context import notebook_execution_context
allocation_names = ['Legacy 45d'] + [short_results[short_results.Inputs.eq(n)].sort_values('CAGR',ascending=False).iloc[0].Configuration for n in (3,4)]
balanced_four = long_results[long_results.Inputs.eq(4)].sort_values('CAGR',ascending=False).iloc[0].Configuration
if balanced_four not in allocation_names:
    allocation_names.append(balanced_four)
allocation_figures = {}
for name in allocation_names:
    weights=calculate_asset_weights(retained[name]['result'].state)
    allocation_figures[name]=visualise_weights(weights,normalised=False,include_reserves=True)
colours=allocation_colours(list(allocation_figures.values()))
ceiling=max(float(retained[name]['equity'].max()) for name in allocation_names)*1.05
for name,fig in allocation_figures.items():
    chart_intro(f'Absolute asset allocation — {label(name)}', 'Stacked holding values and cash in US dollars; the total follows portfolio equity. This shows how changing ranking inputs changes the funded basket.', SHORT_PERIOD)
    fig.update_layout(title=f'Absolute allocation — {label(name)}',width=1550,height=1050)
    style_allocation(fig,colours,ceiling)
    show_static(fig, SHORT_PERIOD)

Retained candidate states — complete

### Equity paths of retained supports — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Labels identify the clipping family, input count and support number; full coefficients are listed above. All start with $150,000 and no inherited positions.

### Quarterly profit and loss — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Compounded daily portfolio returns on a common colour scale. The final quarter is partial.

### Absolute asset allocation — Legacy 45d — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Stacked holding values and cash in US dollars; the total follows portfolio equity. This shows how changing ranking inputs changes the funded basket.

### Absolute asset allocation — Blend 46d · 3 inputs · support 04 — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Stacked holding values and cash in US dollars; the total follows portfolio equity. This shows how changing ranking inputs changes the funded basket.

### Absolute asset allocation — Legacy 45d · 4 inputs · support 13 — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Stacked holding values and cash in US dollars; the total follows portfolio equity. This shows how changing ranking inputs changes the funded basket.

### Absolute asset allocation — Legacy 45d · 4 inputs · support 04 — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Stacked holding values and cash in US dollars; the total follows portfolio equity. This shows how changing ranking inputs changes the funded basket.

## Profit concentration and large moves

Check whether a candidate’s performance comes from one vault or one exceptional day. These diagnostics do not change strategy parameters.

In [7]:
from tradingstrategy.binance.price import fetch_binance_price
with compact_output('Position attribution and market context'):
    market={symbol:fetch_binance_price(symbol=symbol,start=PERIODS['2026'][0]-datetime.timedelta(days=7))['open'] for symbol in ('BTCUSDT','ETHUSDT')}
    robustness, contributors, jumps, positions = attribution(chart_runs,market)
    for name,frame in [('2026-robustness',robustness),('2026-contributors',contributors),('2026-jumps',jumps),('2026-positions',positions)]:
        frame.to_csv(ARTIFACT_DIR/f'{name}.csv',index=False)
present_table(robustness[['Configuration','Best day','Best day return','Excess kurtosis','Leading vault','Leader share of positive vault PnL','Sharpe with best day zeroed','Sharpe without leader (fixed ledger)']].style.format({'Best day return':'{:.2%}','Excess kurtosis':'{:.2f}','Leader share of positive vault PnL':'{:.1%}','Sharpe with best day zeroed':'{:.2f}','Sharpe without leader (fixed ledger)':'{:.2f}'}), 'Dependence on the best day and leading vault', 'Best-day removal and leading-vault PnL removal retain the original trade ledger. These are sensitivities, not executable exclusion strategies; attribution must reconcile to equity.', SHORT_PERIOD)
present_table(jumps, 'Three largest portfolio days and market context', 'Vault contribution and BTC/ETH returns use the same interval between portfolio valuations. Curator flags are descriptive, not retroactive filters.', SHORT_PERIOD, collapsed=True)
present_table(contributors, 'Leading vaults and curator annotations', 'The five largest final vault contributors for each retained path, with existing curator quality/exclusion annotations.', SHORT_PERIOD, collapsed=True)

Position attribution and market context — complete

### Dependence on the best day and leading vault — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Best-day removal and leading-vault PnL removal retain the original trade ledger. These are sensitivities, not executable exclusion strategies; attribution must reconcile to equity.

### Three largest portfolio days and market context — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Vault contribution and BTC/ETH returns use the same interval between portfolio valuations. Curator flags are descriptive, not retroactive filters.

### Leading vaults and curator annotations — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

The five largest final vault contributors for each retained path, with existing curator quality/exclusion annotations.

## Completion and provenance

Save the complete grid, retained paths and input fingerprints for later agents to analyse.

In [8]:
(ARTIFACT_DIR/'completed.json').write_text(json.dumps({'short_configurations':len(short_results),'long_configurations':len(long_results),'retained_2026_paths':selected_names,'source_replication':True,'engine_calls':evaluator.engine_calls,'fingerprint':evaluator.fingerprint,'maximum_attribution_residual_usd':float(robustness['Attribution residual (USD)'].max())},indent=2))
present_table(pd.DataFrame([{'Short configurations':len(short_results),'Full-history configurations':len(long_results),'Source/exact equity and ledger match':True,'Maximum attribution residual (USD)':robustness['Attribution residual (USD)'].max()}]), 'Completed experiment', 'Both periods completed with fixed parameters. Generated data, states and manifests are ignored; the notebook retains reviewable outputs.', SHORT_PERIOD)

### Completed experiment — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Both periods completed with fixed parameters. Generated data, states and manifests are ignored; the notebook retains reviewable outputs.

,Short configurations,Full-history configurations,Source/exact equity and ledger match,Maximum attribution residual (USD)
0,74,74,True,5.820766e-11

## Additional-signal availability — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Distinct non-zero coefficients do not guarantee distinct information. This audit measures undefined composite scores and each input's availability, clipping saturation and variation across funded vaults. Dollar fractions use requested final targets, not realised time-weighted exposure. Variation within the funded basket does not measure predictive power or the whole eligible universe.

| Configuration | Inputs | Funded target rows | Unscored target dollars |
| --- | --- | --- | --- |
| Legacy 45d | 2 | 834 | 0.0% |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 4 | 834 | 0.0% |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 4 | 834 | 0.0% |
| Blend 46d | 2 | 834 | 0.0% |
| Blend 46d / 3 inputs / 6m CAGR | 3 | 834 | 0.0% |
| Blend 46d / 3 inputs / 1m Sortino | 3 | 834 | 0.0% |

<details><summary>Per-input activity and clipping — 2026-01-01 → 2026-10-05 (end exclusive, UTC)</summary>

Each coefficient is meaningful by design, but a clipped input can be constant across the funded basket. Missing inputs follow the unchanged source unscored behaviour.

| Configuration | Feature | Coefficient | Available target dollars | At maximum score | Funded dates with varying score |
| --- | --- | --- | --- | --- | --- |
| Legacy 45d | 45d compatibility Sortino | 40.0% | 100.0% | 81.7% | 54.0% |
| Legacy 45d | 1y CAGR | 60.0% | 100.0% | 42.1% | 100.0% |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 1m Sortino | 10.0% | 100.0% | 79.0% | 65.5% |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 45d compatibility Sortino | 32.0% | 100.0% | 82.3% | 54.7% |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 6m CAGR | 10.0% | 100.0% | 38.3% | 100.0% |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 1y CAGR | 48.0% | 100.0% | 41.2% | 100.0% |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 45d compatibility Sortino | 32.0% | 100.0% | 83.6% | 55.4% |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 2m CAGR | 10.0% | 100.0% | 51.7% | 89.2% |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 6m Sortino | 10.0% | 100.0% | 51.6% | 95.7% |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 1y CAGR | 48.0% | 100.0% | 42.9% | 100.0% |
| Blend 46d | 46d Sortino | 40.0% | 100.0% | 58.8% | 95.0% |
| Blend 46d | 1y CAGR | 60.0% | 100.0% | 37.1% | 100.0% |
| Blend 46d / 3 inputs / 6m CAGR | 46d Sortino | 32.0% | 100.0% | 54.6% | 95.0% |
| Blend 46d / 3 inputs / 6m CAGR | 6m CAGR | 20.0% | 100.0% | 40.1% | 100.0% |
| Blend 46d / 3 inputs / 6m CAGR | 1y CAGR | 48.0% | 100.0% | 42.2% | 100.0% |
| Blend 46d / 3 inputs / 1m Sortino | 1m Sortino | 20.0% | 100.0% | 68.4% | 87.1% |
| Blend 46d / 3 inputs / 1m Sortino | 46d Sortino | 32.0% | 100.0% | 65.3% | 92.8% |
| Blend 46d / 3 inputs / 1m Sortino | 1y CAGR | 48.0% | 100.0% | 34.1% | 100.0% |

</details>

## Does an extra lookback add information? — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Collapse every additional CAGR/Sortino lookback into the original core lookback while preserving total weight on each metric, clipping recipes, sizing and selection. Other metric inputs stay unchanged. These post-selection diagnostic backtests distinguish an extra window from merely changing the CAGR/Sortino balance; they are exploratory and are not a new optimiser.

| Configuration | Original inputs | Collapsed inputs | Candidate CAGR | Collapsed CAGR | Candidate Sharpe | Collapsed Sharpe | Candidate max DD | Collapsed max DD |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Blend 46d / 3 inputs / 1m Sortino | 3 | 2 | 39.26% | 26.67% | 2.05 | 1.49 | -4.93% | -5.77% |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 4 | 2 | 51.77% | 41.89% | 2.30 | 1.99 | -6.35% | -6.39% |
| Blend 46d / 3 inputs / 6m CAGR | 3 | 2 | 51.99% | 42.76% | 2.29 | 2.03 | -7.29% | -5.85% |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 4 | 2 | 52.30% | 41.89% | 2.23 | 1.99 | -7.62% | -6.39% |

<details><summary>Same metric-mass controls over full history — 2023-03-01 → 2026-10-05 (end exclusive, UTC)</summary>

Independent fresh-start runs on the same inputs. Feature counts can remain above two when the original candidate contains an additional metric such as Sharpe.

| Configuration | Original inputs | Collapsed inputs | Candidate CAGR | Collapsed CAGR | Candidate Sharpe | Collapsed Sharpe | Candidate max DD | Collapsed max DD |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Blend 46d / 3 inputs / 1m Sortino | 3 | 2 | 17.45% | 16.00% | 1.31 | 1.21 | -9.50% | -8.77% |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 4 | 2 | 22.05% | 15.85% | 1.62 | 1.24 | -8.08% | -7.92% |
| Blend 46d / 3 inputs / 6m CAGR | 3 | 2 | 17.15% | 14.58% | 1.30 | 1.12 | -7.92% | -10.55% |
| Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 4 | 2 | 19.57% | 15.85% | 1.45 | 1.24 | -7.92% | -7.92% |

</details>

## Full-history profit concentration — 2023-03-01 → 2026-10-05 (end exclusive, UTC)

<details><summary>Best-day and leading-vault sensitivities for full-history-selected candidates</summary>

Two-input references and the full-history CAGR/Sharpe leaders at each input count. Position PnL is reconciled to equity; contributor removals retain the original trading ledger and are not exclusion backtests. Full-history curator annotations and BTC/ETH interval context are also saved to CSV.

| Configuration | Best day | Best day return | Leading vault | Leader share of positive vault PnL | Sharpe with best day zeroed | Sharpe without leader (fixed ledger) |
| --- | --- | --- | --- | --- | --- | --- |
| Legacy 45d | 2025-08-14 00:00:00 | 5.4% | Realist Capital | 17.3% | 1.15 | 1.05 |
| Blend 46d | 2025-08-14 00:00:00 | 5.7% | Delta_01 | 16.1% | 1.14 | 0.96 |
| Blend 46d / 3 inputs / 1m Sortino | 2025-10-15 00:00:00 | 7.7% | naze oppa degen nation | 14.5% | 1.20 | 1.11 |
| Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 2025-08-14 00:00:00 | 6.7% | Realist Capital | 15.7% | 1.53 | 1.46 |

</details>

## Interpretation and next research step

### Three and four inputs — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Experiment 04 already evaluated three- and four-input proposals, but only six of each per objective: 12 three-input and 12 four-input proposals in total. It also tested a dense 45-input equal score. Sizing and missing-score semantics varied during that search, and coefficient refinements stayed on the winning support. The two-input selected formulas were therefore not evidence that additional inputs could not help.

Experiment 06 holds sizing and selection fixed. The strongest balanced candidate is:

`0.48 × clip(CAGR360 / 1.0, 0, 1) + 0.32 × clip(Sortino45 / 3, 0, 1) + 0.10 × clip(CAGR180 / 1.0, 0, 1) + 0.10 × clip(Sortino30 / 3, 0, 1)`

The 45-day input uses the original source compatibility calculation. Its total metric balance is 58% CAGR / 42% Sortino. Source handling remains unchanged when a component is unavailable. All retained 2026 candidates have finite component scores on their funded target rows; missing additional features can still alter ranking elsewhere in the universe.

The extra windows outperform a two-input 58/42 control in both periods. They do not establish that four unrelated metrics are required: this winner uses two metrics over four windows. Additional Sharpe, maximum drawdown and Calmar inputs were included in the grid, but none led the full-history ranking. Among the funded targets, the leading candidate's 30-day Sortino is saturated at its maximum score for 79.0% of target dollars and differs across funded vaults on 65.5% of decision dates. Counting inputs alone therefore overstates the amount of independent information.

The leading four-input candidate still benefits from the 26 June jump. Its 2026 Sharpe falls from 2.30 to 2.00 when that day's return is zeroed, versus baseline 1.96 to 1.62. Realist Capital contributes 38.4% of positive vault PnL, versus 44.8% for the baseline. Removing its PnL on the fixed ledger leaves Sharpe 1.58, versus baseline 1.10. These are sensitivities, not tradable exclusion replays. Over full history, the candidate's best-day-zeroed Sharpe is 1.53 and its leader contributes 15.7% of positive vault profits. This is broader evidence than one 2026 jump, but it remains in-sample.

Next, refine the leading support's coefficients around 48/32/10/10 and compare against the best two-input controls using chronological training/validation windows. The initial four-input grid covers 18 of 153 possible pairs from the 18 extra features in each family, with fixed coefficients and 20% total added mass. It is a bounded screening exercise, not an exhaustive or global optimum. The long and short periods overlap; neither is an independent holdout.

### Saved-output inspection — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

All eight code cells completed without saved errors or warnings. All charts use 2026 with explicit period subtitles. Visual inspection found an overlapping scatter legend/colour bar and an equity axis labelled “0”; both were corrected. Allocation charts include the full-history four-input leader as well as the short-period maxima, with shared vault colours and a common dollar scale.