# Experiment 07 — scoring inputs and portfolio breadth

Based on [06-opt-score-3-4-inputs.ipynb](06-opt-score-3-4-inputs.ipynb).

## User goal

Repeat the same scoring experiment with **7, 8 and 10 positions allocated**, including the highlighted four-input candidate (360-day CAGR, 45-day Sortino, 180-day CAGR and 30-day Sortino). Keep six positions as the matched reference. An input is a metric/lookback cell, not a distinct metric or a position weight.

## Method

Freeze all 74 experiment 06 supports: two two-input controls, 36 three-input configurations and 36 four-input configurations. Preserve 18 supports per cardinality/family, 60/40 two-input controls and fixed 48/32/20 or 48/32/10/10 coefficients, original and blended clipping recipes, source missing-score behaviour, 90-day inverse-variance sizing, 33% concentration cap, 98% allocation target, parent capacity redistribution and two-day cadence.

Change the maximum positions, maximum capacity positions and entry rank to N; keep the source two-rank exit buffer as N+2. The capacity extension remains disabled because both position limits equal N. Other selector rules, admission guards, universe, thresholds and source-modelled costs remain unchanged. A position limit is a maximum; admission and sizing can produce fewer funded vaults.

Run all supports at N=6, 7, 8 and 10 in **2026-01-01 → 2026-10-05** and **2023-03-01 → 2026-10-05**, end exclusive, UTC, with fresh \$150,000 starts and causal feature observations. There are 296 configurations per period, including 74 verified six-position references, and 444 new replays. Use the exact pinned repaired-data generation from experiment 06. Three independent processes handle the new breadth arms serially, with observable checkpoint progress and separate caches.

## Presentation and interpretation

Default charts and tables use 2026. Full-history evidence is collapsed. Every element has a subheading, description and period. Show fixed-score breadth comparisons separately from observed maxima; wider portfolios are not assumed to be better. Source controls must match complete equity/trade ledgers, and reused six-position metrics must match experiment 06. Analyse individual vault profits, large days, curator annotations, BTC/ETH interval returns, cash usage and best-day/leading-vault sensitivities. The periods overlap and are previously inspected; these are exploratory comparisons, not untouched holdouts or global coefficient optima.
## Key new insights

- **Frozen highlighted score, six-position reference:** 51.77% CAGR, 2.30 Sharpe and -6.35% maximum drawdown in 2026; this matches experiment 06.
- **Highest CAGR among wider versions of that score:** N=7 gives 30.85% CAGR, 1.58 Sharpe and -6.42% drawdown. Highest Sharpe among wider versions is 1.58 at N=7. 0 of the three wider focal variants improve all three metrics against N=6.
- **Highest observed 2026 CAGR in the complete wider grid:** Blend 46d / 7 positions: 47.93% CAGR, 2.46 Sharpe and -4.71% drawdown. Highest observed Sharpe is 2.46 for Blend 46d / 7 positions. These are descriptive search maxima.
- **Matched breadth effects:** 47 of 222 wider score/breadth combinations have higher CAGR and Sharpe with no worse drawdown than their own six-position support. This is not a probability of success or an independent significance test.
- **Highlighted-score conclusion:** all three wider portfolios have lower 2026 CAGR and Sharpe than six positions. Lower cash alone is not an improvement; retain six positions as the reference for this frozen score.
- **Useful alternative, not the highlighted four-input formula:** two-input Blend 46d at seven positions gives 47.93% CAGR, 2.46 Sharpe and -4.71% drawdown in 2026. Full-history CAGR is 18.40%, Sharpe 1.39 and drawdown -8.08%. It improves its own six-position clipping-blend reference in both periods, but does not exceed the four-input six-position CAGR.

## Summary of results

### Highlighted four-input score — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Hold 48% 360-day CAGR, 32% 45-day source-compatible Sortino, 10% 180-day CAGR and 10% 30-day Sortino fixed with legacy clips. Only the position limits and associated entry/exit ranks change. All portfolios start at \$150,000 with no inherited positions. “Maximum vaults held” is realised breadth; the position parameter is a limit.

| Positions | CAGR | Sharpe | Maximum drawdown | Mean cash weight | Maximum vaults held | Trades |
| --- | --- | --- | --- | --- | --- | --- |
| 6 | 51.77% | 2.30 | -6.35% | 10.18% | 6 | 569 |
| 7 | 30.85% | 1.58 | -6.42% | 6.21% | 7 | 726 |
| 8 | 16.24% | 1.04 | -6.57% | 4.35% | 8 | 824 |
| 10 | -3.01% | -0.28 | -6.79% | 2.83% | 10 | 1027 |

<details><summary>Same frozen score over full history — 2023-03-01 → 2026-10-05 (end exclusive, UTC)</summary>

Independent fresh-start replays on the same inputs. Full history overlaps 2026; it is not a holdout.

| Positions | CAGR | Sharpe | Maximum drawdown | Mean cash weight | Maximum vaults held | Trades |
| --- | --- | --- | --- | --- | --- | --- |
| 6 | 22.05% | 1.62 | -8.08% | 43.71% | 6 | 1071 |
| 7 | 17.30% | 1.26 | -9.99% | 40.13% | 7 | 1247 |
| 8 | 14.88% | 1.12 | -11.91% | 37.73% | 8 | 1417 |
| 10 | 8.49% | 0.70 | -17.42% | 34.00% | 10 | 1847 |

</details>

### Observed scoring leaders at each breadth — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

<details><summary>Highest observed CAGR and Sharpe supports, including the six-position reference</summary>

Supports are chosen by inspecting 2026, so these are descriptive comparisons. Coefficients and clips remain the predeclared experiment 06 settings.

| Objective | Positions | Score | Inputs | CAGR | Sharpe | Maximum drawdown | Mean cash weight |
| --- | --- | --- | --- | --- | --- | --- | --- |
| CAGR | 6 | Legacy 45d / 4 inputs / 6m Sortino + 2m CAGR | 4 | 52.30% | 2.23 | -7.62% | 8.41% |
| Sharpe | 6 | Legacy 45d / 4 inputs / 6m CAGR + 1m Sortino | 4 | 51.77% | 2.30 | -6.35% | 10.18% |
| CAGR | 7 | Blend 46d | 2 | 47.93% | 2.46 | -4.71% | 5.03% |
| Sharpe | 7 | Blend 46d | 2 | 47.93% | 2.46 | -4.71% | 5.03% |
| CAGR | 8 | Blend 46d / 4 inputs / 3m CAGR + 1y Sharpe | 4 | 29.92% | 1.99 | -5.16% | 4.78% |
| Sharpe | 8 | Blend 46d / 4 inputs / 3m CAGR + 1y Sharpe | 4 | 29.92% | 1.99 | -5.16% | 4.78% |
| CAGR | 10 | Legacy 45d / 4 inputs / 1y Sortino + 3m CAGR | 4 | 14.52% | 1.46 | -4.12% | 3.81% |
| Sharpe | 10 | Legacy 45d / 4 inputs / 1y Sortino + 3m CAGR | 4 | 14.52% | 1.46 | -4.12% | 3.81% |

</details>

### Matched effects across all 74 supports — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Compare each support against itself with six positions. Changes in percentage metrics are percentage points. Positive cash-weight change means more cash held; each breadth arm contains 74 paired comparisons.

| Positions | Median CAGR change | Median Sharpe change | Median cash-weight change | Joint improvements |
| --- | --- | --- | --- | --- |
| 7 | -3.05% | +0.03 | -2.43% | 29 |
| 8 | -12.94% | -0.40 | -3.85% | 12 |
| 10 | -24.81% | -0.87 | -3.96% | 6 |

## Robustness of results

All 296 configurations completed both periods: 444 new wider-position replays and 148 verified six-position references. Source v11 and the exact two-input wrapper match complete equity and every trade in both periods. Every six-position result matches experiment 06's metrics. Realised vault counts never exceed their assigned limits. Position attribution reconciles to equity with a maximum residual of 2.04e-10 USD.

The selector algorithm remains the source implementation, but its cardinality-related entry/exit ranks change from 6/8 to N/(N+2). The 33% concentration cap, 98% allocation target, sizing lookback, clipping recipes, missing-score handling, admission checks and rebalancing costs remain fixed. Wider breadth is therefore not a standalone change in diversification: it also changes which ranks can enter and be retained. The engine follows the existing parent allocation and pinning rules rather than guaranteeing exactly N funded vaults on every decision.

- **Fixed score, N=6:** leading vault Realist Capital contributes 38.4% of positive vault profits. Best day 2026-06-26 returns 6.80%; excess kurtosis 12.08. Sharpe is 2.00 with that return zeroed and 1.58 after removing the leader PnL on the fixed ledger.
- **Fixed score, N=7:** leading vault Realist Capital contributes 34.4% of positive vault profits. Best day 2026-06-26 returns 5.62%; excess kurtosis 11.76. Sharpe is 1.25 with that return zeroed and 0.81 after removing the leader PnL on the fixed ledger.
- **Fixed score, N=8:** leading vault Realist Capital contributes 23.6% of positive vault profits. Best day 2026-06-26 returns 4.23%; excess kurtosis 15.55. Sharpe is 0.72 with that return zeroed and 0.58 after removing the leader PnL on the fixed ledger.
- **Fixed score, N=10:** leading vault 22Cap contributes 17.7% of positive vault profits. Best day 2026-08-23 returns 2.32%; excess kurtosis 17.01. Sharpe is -0.63 with that return zeroed and -0.54 after removing the leader PnL on the fixed ledger.

On 24 June, Realist Capital supplies 99.7% of positive vault PnL in the focal six-position portfolio, while BTC and ETH return -0.91% and -2.33% over the matching interval. It is not curator-excluded or quarantined at that date. These gains are vault-specific rather than a broad market rise; short or hedged vault profits can still be valid. The leading-vault and best-day sensitivities above quantify the dependence without applying post-hoc exclusions.

### Full-history sensitivity of the highlighted score — 2023-03-01 → 2026-10-05 (end exclusive, UTC)

<details><summary>Best-day and leading-vault sensitivities</summary>

These remove booked returns or contributor PnL without rerunning selection; they are sensitivities, not tradable exclusion strategies. Curator annotations and matching BTC/ETH returns are saved in the notebook and detailed artefacts.

| Positions | Leading vault | Leader share of positive PnL | Best day | Best day return | Sharpe with best day zeroed | Sharpe without leader |
| --- | --- | --- | --- | --- | --- | --- |
| 6 | Realist Capital | 15.7% | 2025-08-14 | 6.71% | 1.53 | 1.46 |
| 7 | Realist Capital | 14.9% | 2025-08-14 | 6.50% | 1.16 | 1.06 |
| 8 | Realist Capital | 11.1% | 2025-08-14 | 6.41% | 1.02 | 0.95 |
| 10 | Hyperliquidity Provider (HLP) | 16.5% | 2025-08-14 | 6.12% | 0.58 | 0.46 |

</details>

The full and short histories overlap and have already been inspected. The support grid and fixed coefficient mass are bounded; these results do not demonstrate an unseen-time optimum. Current membership/guard assumptions, carried NAV observations, weak historical permission coverage and concentration in individual vaults remain limitations. Default charts and tables use 2026 with explicit period titles. Generated caches, logs and states are ignored; reviewable findings and saved notebook outputs remain outside generated artefact directories.


### Saved-output inspection — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

All seven code cells completed, with nine saved PNG charts and no saved errors or warnings. Visual inspection covered every chart. Allocation legends initially clipped the final vault names; a common chart height based on the largest legend now shows every name. Heatmap titles explicitly identify percentage units, and the two-input breadth controls have their own described table. Charts and default performance tables use 2026; full-history evidence is collapsed.

## Inputs and frozen experiment design

Verify the parent fingerprint before launching the breadth grid.

In [1]:
from pathlib import Path
import sys
RESEARCH_DIR=Path('/Users/moo/code/getting-started/scratchpad/hyperliquid-vov-2nd')
sys.path.insert(0,str(RESEARCH_DIR))
from score_matrix_visualisation import compact_output, chart_intro, present_table, metric_table, show_static, style_allocation, allocation_colours
with compact_output('Pinned parent inputs and breadth design'):
    import json
    import datetime
    import numpy as np
    import pandas as pd
    import plotly.express as px
    from tradeexecutor.utils.notebook import setup_charting_and_output, OutputMode
    from score_position_count_experiment import *
    from score_calibration_report import attribution, quarterly_figure
    setup_charting_and_output(OutputMode.static,image_format='png',width=1500,height=900)
    evaluator,parameters,candidates,generation=initialise()
    lookup={row['Configuration']:row for row in candidates}
    assert parameters.inverse_vol_window==90 and parameters.max_concentration_pct==.33
present_table(pd.DataFrame([{'Positions':n,'Entry rank':n,'Exit rank':n+2,'Capacity limit':n,'Configurations per period':74} for n in ExperimentParameters.position_counts]),
              'Position and rank limits', 'Position breadth and its associated entry/exit ranks are the only treatment axis. Scoring supports and other rules are frozen.', SHORT_PERIOD)
present_table(pd.DataFrame([{'Family':family,'Inputs':count,'Supports':sum(r['Family']==family and r['Inputs']==count for r in candidates)} for family in ('Legacy 45d','Blend 46d') for count in (2,3,4)]),
              'Frozen scoring supports', 'Each support is repeated at all four breadth settings; total added-feature mass stays at 20%.', SHORT_PERIOD)

Pinned parent inputs and breadth design — complete

### Position and rank limits — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Position breadth and its associated entry/exit ranks are the only treatment axis. Scoring supports and other rules are frozen.

   Positions  Entry rank  Exit rank  Capacity limit  Configurations per period
0          6           6          8               6                         74
1          7           7          9               7                         74
2          8           8         10               8                         74
3         10          10         12              10                         74

### Frozen scoring supports — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Each support is repeated at all four breadth settings; total added-feature mass stays at 20%.

       Family  Inputs  Supports
0  Legacy 45d       2         1
1  Legacy 45d       3        18
2  Legacy 45d       4        18
3   Blend 46d       2         1
4   Blend 46d       3        18
5   Blend 46d       4        18

## Replication and matching controls

Six-position source checks establish the same starting point as experiment 06.

In [2]:
def trade_ledger(run):
    return [(t.pair.pool_address,t.opened_at,t.executed_at,t.executed_quantity,t.executed_reserve,t.executed_price) for t in run['result'].state.portfolio.get_all_trades()]
replication=[]
with compact_output('Original source and parent replication'):
    row=lookup['Legacy 45d']
    for period in PERIODS:
        source=evaluator.run(row['Weights'],*PERIODS[period],n=6,sizing='inverse_variance',missing=True,profile='legacy',source_control=True,keep=True)
        exact=evaluate(evaluator,row,period,6,keep=True)
        assert np.allclose(source['equity'],exact['equity'],rtol=0,atol=1e-6)
        assert trade_ledger(source)==trade_ledger(exact)
        replication.append({'Period':period,'Final equity (USD)':source['metrics']['Final equity (USD)'],'Trades':source['metrics']['Trades'],'Equity and complete ledger match':True})
present_table(pd.DataFrame(replication).query("Period=='2026'"), 'Original v11 replication', 'Source v11 and the exact two-input wrapper match every trade and the full equity path. The same checks pass over full history.', SHORT_PERIOD)
pd.DataFrame(replication).to_csv(ARTIFACT_DIR/'replication.csv',index=False)

Original source and parent replication — complete

### Original v11 replication — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Source v11 and the exact two-input wrapper match every trade and the full equity path. The same checks pass over full history.

  Period  Final equity (USD)  Trades  Equity and complete ledger match
1   2026       194520.812686     581                              True

## Matched breadth grid

Run all predeclared combinations and save progress after each replay.

In [3]:
with compact_output('Full scoring and position-count grid'):
    short_results,long_results=run_grid(evaluator,candidates,generation)
columns=['Positions','Family','Inputs','Added inputs','CAGR','Sharpe','Maximum drawdown','Mean cash weight','Trades','Maximum vaults held']
focal_short=short_results[short_results.Score.eq(FOCAL_SCORE)].sort_values('Positions')
focal_long=long_results[long_results.Score.eq(FOCAL_SCORE)].sort_values('Positions')
present_table(metric_table(focal_short[columns],f'Fixed four-input score — {SHORT_PERIOD}'), 'Highlighted four-input score across breadth', 'Hold 48% CAGR360 + 32% Sortino45 + 10% CAGR180 + 10% Sortino30 fixed with legacy clips; compare only position/rank limits.', SHORT_PERIOD)
control_short=short_results[short_results.Inputs.eq(2)].sort_values(['Family','Positions'])
present_table(metric_table(control_short[columns],f'Two-input controls across breadth — {SHORT_PERIOD}'), 'Two-input controls across breadth', 'Within each family, hold the 60/40 CAGR/Sortino score fixed and vary only position/rank limits. This distinguishes breadth effects from changing the scoring formula.', SHORT_PERIOD)
present_table(metric_table(focal_long[columns],f'Fixed four-input score — {LONG_PERIOD}'), 'Full-history fixed-score comparison', 'Same frozen score, independent fresh starts; full history overlaps 2026.', LONG_PERIOD,collapsed=True)
present_table(metric_table(short_results[columns].sort_values('CAGR',ascending=False),f'All 296 configurations — {SHORT_PERIOD}'), 'Complete scoring and breadth comparison', 'Every row is an actual replay or a verified experiment 06 reference; colour indicates return/risk metrics.', SHORT_PERIOD,collapsed=True)
present_table(metric_table(long_results[columns],f'All 296 configurations — {LONG_PERIOD}'), 'Complete full-history evidence', 'No candidate or objective is retuned for this table.', LONG_PERIOD,collapsed=True)

Full scoring and position-count grid — complete

### Highlighted four-input score across breadth — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Hold 48% CAGR360 + 32% Sortino45 + 10% CAGR180 + 10% Sortino30 fixed with legacy clips; compare only position/rank limits.

### Two-input controls across breadth — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Within each family, hold the 60/40 CAGR/Sortino score fixed and vary only position/rank limits. This distinguishes breadth effects from changing the scoring formula.

### Full-history fixed-score comparison — 2023-03-01 → 2026-10-05 (end exclusive, UTC)

Same frozen score, independent fresh starts; full history overlaps 2026.

### Complete scoring and breadth comparison — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Every row is an actual replay or a verified experiment 06 reference; colour indicates return/risk metrics.

### Complete full-history evidence — 2023-03-01 → 2026-10-05 (end exclusive, UTC)

No candidate or objective is retuned for this table.

## Observed maxima and matched changes

Keep the fixed highlighted score separate from winners selected by inspecting each period.

In [4]:
selection_rows=[]
for chosen_on,frame in [('Full history',long_results),('2026 descriptive',short_results)]:
    for n in ExperimentParameters.position_counts:
        for objective in ('CAGR','Sharpe'):
            best=frame[frame.Positions.eq(n)].sort_values([objective,'Configuration'],ascending=[False,True]).iloc[0]
            replay=short_results[short_results.Configuration.eq(best.Configuration)].iloc[0]
            selection_rows.append({'Selected on':chosen_on,'Objective':objective,**replay.to_dict()})
present_table(metric_table(pd.DataFrame(selection_rows)[['Selected on','Objective',*columns]],f'Observed winners replayed in 2026 — {SHORT_PERIOD}'), 'Selection provenance and 2026 performance', 'All metric columns are 2026 replays; the first columns say which period selected the support. These are descriptive maxima.', SHORT_PERIOD,collapsed=True)
pd.DataFrame(selection_rows).to_csv(ARTIFACT_DIR/'selection-provenance.csv',index=False)
deltas=matched_deltas(short_results)
deltas.to_csv(ARTIFACT_DIR/'2026-matched-deltas.csv',index=False)
summary=deltas.groupby(['Positions','Inputs']).agg(**{'Mean CAGR change':('Delta CAGR','mean'),'Median CAGR change':('Delta CAGR','median'),'Mean Sharpe change':('Delta Sharpe','mean'),'Joint improvement fraction':('Joint improvement','mean')}).reset_index()
present_table(summary.style.format({'Mean CAGR change':'{:+.2%}','Median CAGR change':'{:+.2%}','Mean Sharpe change':'{:+.2f}','Joint improvement fraction':'{:.1%}'}).background_gradient(subset=['Mean CAGR change','Median CAGR change','Mean Sharpe change'],cmap='RdYlGn'), 'Matched effects of adding positions', 'Each support is compared with itself at six positions. Joint improvement requires higher CAGR and Sharpe with no worse drawdown; these fractions do not measure statistical significance.', SHORT_PERIOD)

### Selection provenance and 2026 performance — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

All metric columns are 2026 replays; the first columns say which period selected the support. These are descriptive maxima.

### Matched effects of adding positions — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Each support is compared with itself at six positions. Joint improvement requires higher CAGR and Sharpe with no worse drawdown; these fractions do not measure statistical significance.

## Parameter-space maps

Compare the whole search rather than only the observed leaders.

In [5]:
for count in (3,4):
    chart_intro(f'Exactly {count} inputs across breadth settings', 'Rows identify additional metric/lookback cells; columns are maximum positions. Colours share the same metric scale across clipping families. Higher signed drawdown is better.', SHORT_PERIOD)
    fig=metric_heatmap(short_results,count)
    for annotation in fig.layout.annotations:
        if annotation.text.endswith(('CAGR','Maximum drawdown')):
            annotation.text+=' (%)'
    show_static(fig,SHORT_PERIOD)
chart_intro('Return and risk clusters', 'Colour is position count; circles, diamonds and squares are two-, three- and four-input scores. Each point is an actual configuration; both clipping families are included.', SHORT_PERIOD)
show_static(cluster_figure(short_results),SHORT_PERIOD)

### Exactly 3 inputs across breadth settings — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Rows identify additional metric/lookback cells; columns are maximum positions. Colours share the same metric scale across clipping families. Higher signed drawdown is better.

### Exactly 4 inputs across breadth settings — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Rows identify additional metric/lookback cells; columns are maximum positions. Colours share the same metric scale across clipping families. Higher signed drawdown is better.

### Return and risk clusters — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Colour is position count; circles, diamonds and squares are two-, three- and four-input scores. Each point is an actual configuration; both clipping families are included.

## Equity, quarterly returns and absolute allocation

Retain the fixed focal score and separately identified observed leaders for attribution.

In [6]:
selected_names=selected_configurations(short_results,long_results)
with compact_output('Retained 2026 paths'):
    print(f'Retaining {len(selected_names)} paths; estimated 1–3 minutes if states must be rebuilt.')
    retained={}
    for name in tqdm(selected_names,desc='Retained 2026 states'):
        row=short_results[short_results.Configuration.eq(name)].iloc[0]
        run=evaluate(evaluator,lookup[row.Score],'2026',row.Positions,keep=True)
        assert all(np.isclose(value,row[metric],rtol=1e-12,atol=1e-8) for metric,value in run['metrics'].items())
        retained[name]=run
    print(f'Retained {len(retained)} paths for position attribution.')
focal_names=focal_short.Configuration.tolist()
focal_runs={f'N={int(row.Positions)}':retained[row.Configuration] for _,row in focal_short.iterrows()}
equity=pd.DataFrame({name:run['equity'] for name,run in focal_runs.items()});equity.index.name='Date'
chart_intro('Equity of the fixed four-input score', 'Identical coefficients and clips at four breadth limits; all portfolios start with $150,000 and no inherited positions.', SHORT_PERIOD)
show_static(px.line(equity,title='Fixed four-input score: equity by position count',width=1550,height=650,template='plotly_white',labels={'value':'Portfolio equity (USD)','variable':'Positions'}),SHORT_PERIOD)
chart_intro('Quarterly returns of the fixed four-input score', 'Compounded daily returns with a common zero-centred scale; the last quarter is partial.', SHORT_PERIOD)
show_static(quarterly_figure(focal_runs).update_layout(title='Fixed four-input score: quarterly returns by breadth'),SHORT_PERIOD)
from tradeexecutor.analysis.weights import calculate_asset_weights,visualise_weights
figures={name:visualise_weights(calculate_asset_weights(run['result'].state),normalised=False,include_reserves=True) for name,run in focal_runs.items()}
colours=allocation_colours(list(figures.values()));ceiling=max(run['equity'].max() for run in focal_runs.values())*1.05
allocation_height=max(1050,20*max(len(fig.data) for fig in figures.values())+180)
for name,fig in figures.items():
    chart_intro(f'Absolute asset allocation — {name}', 'Holding values and cash in US dollars for the fixed four-input score. Shared colours and a common dollar scale allow breadth comparisons.', SHORT_PERIOD)
    fig.update_layout(title=f'Fixed four-input score: absolute allocation — {name}',width=1550,height=allocation_height)
    style_allocation(fig,colours,ceiling)
    show_static(fig,SHORT_PERIOD)

Retained 2026 paths — complete

### Equity of the fixed four-input score — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Identical coefficients and clips at four breadth limits; all portfolios start with $150,000 and no inherited positions.

### Quarterly returns of the fixed four-input score — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Compounded daily returns with a common zero-centred scale; the last quarter is partial.

### Absolute asset allocation — N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Holding values and cash in US dollars for the fixed four-input score. Shared colours and a common dollar scale allow breadth comparisons.

### Absolute asset allocation — N=7 — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Holding values and cash in US dollars for the fixed four-input score. Shared colours and a common dollar scale allow breadth comparisons.

### Absolute asset allocation — N=8 — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Holding values and cash in US dollars for the fixed four-input score. Shared colours and a common dollar scale allow breadth comparisons.

### Absolute asset allocation — N=10 — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Holding values and cash in US dollars for the fixed four-input score. Shared colours and a common dollar scale allow breadth comparisons.

## Position and jump robustness

Reconcile portfolio profit, inspect individual vaults and compare market intervals.

In [7]:
from tradingstrategy.binance.price import fetch_binance_price
with compact_output('Vault attribution and full-history confirmation'):
    market={symbol:fetch_binance_price(symbol=symbol,start=PERIODS['Long'][0]-datetime.timedelta(days=7))['open'] for symbol in ('BTCUSDT','ETHUSDT')}
    chart_runs={short_label(short_results[short_results.Configuration.eq(name)].iloc[0]):run for name,run in retained.items()}
    robustness,contributors,jumps,positions=attribution(chart_runs,market)
    for name,frame in [('2026-robustness',robustness),('2026-contributors',contributors),('2026-jumps',jumps),('2026-positions',positions)]:frame.to_csv(ARTIFACT_DIR/f'{name}.csv',index=False)
    long_names=focal_long.Configuration.tolist()
    for n in ExperimentParameters.position_counts:
        for objective in ('CAGR','Sharpe'):
            long_names.append(long_results[long_results.Positions.eq(n)].sort_values(objective,ascending=False).iloc[0].Configuration)
    print(f'Retaining {len(set(long_names))} full-history paths; estimated 2–4 minutes if states must be rebuilt.')
    long_runs={}
    for name in tqdm(list(dict.fromkeys(long_names)),desc='Retained full-history states'):
        row=long_results[long_results.Configuration.eq(name)].iloc[0]
        long_runs[short_label(row)]=evaluate(evaluator,lookup[row.Score],'Long',row.Positions,keep=True)
    robust_long,contributors_long,jumps_long,positions_long=attribution(long_runs,market)
    for name,frame in [('Long-robustness',robust_long),('Long-contributors',contributors_long),('Long-jumps',jumps_long),('Long-positions',positions_long)]:frame.to_csv(ARTIFACT_DIR/f'{name}.csv',index=False)
robust_columns=['Configuration','Best day','Best day return','Excess kurtosis','Leading vault','Leader share of positive vault PnL','Sharpe with best day zeroed','Sharpe without leader (fixed ledger)']
formatting={'Best day return':'{:.2%}','Excess kurtosis':'{:.2f}','Leader share of positive vault PnL':'{:.1%}','Sharpe with best day zeroed':'{:.2f}','Sharpe without leader (fixed ledger)':'{:.2f}'}
present_table(robustness[robust_columns].style.format(formatting), 'Best-day and leading-vault sensitivities', 'The fixed focal score, baseline and selected maxima are audited. Removing a day or leader PnL retains the original ledger; these are sensitivities, not executable exclusion strategies.',SHORT_PERIOD)
present_table(jumps, 'Largest portfolio days and BTC/ETH intervals', 'The leading vault contribution and market returns use the same interval between portfolio valuations; curator flags are descriptive, not retroactive exclusions.',SHORT_PERIOD,collapsed=True)
present_table(contributors, 'Leading vault contributors and curator annotations', 'Five largest final contributors per retained path, using existing curator quality/exclusion annotations.',SHORT_PERIOD,collapsed=True)
present_table(robust_long[robust_columns].style.format(formatting), 'Full-history position concentration', 'Same diagnostics for the frozen focal score and full-history-selected leaders; this period overlaps the default replay.',LONG_PERIOD,collapsed=True)
maximum_residual=max(robustness['Attribution residual (USD)'].max(),robust_long['Attribution residual (USD)'].max())
(ARTIFACT_DIR/'completed.json').write_text(json.dumps({'short_configurations':len(short_results),'long_configurations':len(long_results),'source_replication':True,'six_position_parent_replication':True,'maximum_attribution_residual_usd':float(maximum_residual),'fingerprint':evaluator.fingerprint},indent=2))
present_table(pd.DataFrame([{'2026 configurations':len(short_results),'Full-history configurations':len(long_results),'Source equity/ledger match':True,'Parent six-position metrics match':True,'Maximum attribution residual (USD)':maximum_residual}]), 'Completed experiment', 'All predeclared combinations completed; position limits and profit reconciliation pass. Generated artefacts are ignored and outputs remain in the notebook.', SHORT_PERIOD)

Vault attribution and full-history confirmation — complete

### Best-day and leading-vault sensitivities — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

The fixed focal score, baseline and selected maxima are audited. Removing a day or leader PnL retains the original ledger; these are sensitivities, not executable exclusion strategies.

### Largest portfolio days and BTC/ETH intervals — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

The leading vault contribution and market returns use the same interval between portfolio valuations; curator flags are descriptive, not retroactive exclusions.

### Leading vault contributors and curator annotations — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

Five largest final contributors per retained path, using existing curator quality/exclusion annotations.

### Full-history position concentration — 2023-03-01 → 2026-10-05 (end exclusive, UTC)

Same diagnostics for the frozen focal score and full-history-selected leaders; this period overlaps the default replay.

### Completed experiment — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

All predeclared combinations completed; position limits and profit reconciliation pass. Generated artefacts are ignored and outputs remain in the notebook.

,2026 configurations,Full-history configurations,Source equity/ledger match,Parent six-position metrics match,Maximum attribution residual (USD)
0,296,296,True,True,2.037268e-10

## How breadth changes the highlighted score — 2026-01-01 → 2026-10-05 (end exclusive, UTC)

### Realised holdings and funded scores

Mean holdings are calculated across daily carried portfolio valuations. Score averages use requested final target dollars, not realised time-weighted exposure. Removing Pepe vs PnL retains the original trading ledger and is a sensitivity, not an exclusion backtest. Cash is realised; missing component scores follow source semantics. A lower funded score is a ranking description, not a proof of lower future returns.

| Positions | Mean realised vaults | Maximum realised vaults | Mean cash weight | Target-dollar-weighted score | Unscored target dollars | Final total vault PnL (USD) |
| --- | --- | --- | --- | --- | --- | --- |
| 6 | 5.99 | 6 | 10.18% | 0.82 | 0.00% | \$55,430 |
| 7 | 6.96 | 7 | 6.21% | 0.78 | 0.00% | \$33,638 |
| 8 | 7.86 | 8 | 4.35% | 0.74 | 0.00% | \$17,912 |
| 10 | 9.51 | 10 | 2.83% | 0.68 | 0.00% | \$-3,574 |

### Sensitivity to Pepe vs

The seven-position variant deposits \$22,983 on 8 July and redeems \$15,772 on 10 July, losing \$7,211 as modelled NAV falls by about 31%. It has no current curator exclusion or entry-date quarantine flag. Remove all this vault's PnL from the fixed trading ledger to see how much this one loss explains. The seven-position Sharpe rises to 1.97 and CAGR to 37.69%, still below six positions; no exclusion is applied to the strategy results.

| Positions | Pepe vs PnL (USD) | CAGR without Pepe vs (fixed ledger) | Sharpe without Pepe vs (fixed ledger) |
| --- | --- | --- | --- |
| 6 | \$0 | 51.77% | 2.30 |
| 7 | \$-7,211 | 37.69% | 1.97 |
| 8 | \$-3,077 | 19.06% | 1.22 |
| 10 | \$-544 | -2.54% | -0.23 |

### Shared vaults versus additional holdings

Reconcile the final PnL difference against six positions into vaults traded by both variants and vaults traded only by the wider variant. Shared-vault PnL changes include entry/exit timing, different position sizes and compounding; they cannot be attributed to simple weight dilution alone.

| Positions | Total PnL change (USD) | PnL change in shared vaults (USD) | Wider-only vault PnL (USD) |
| --- | --- | --- | --- |
| 7 | \$-21,792 | \$-11,597 | \$-10,195 |
| 8 | \$-37,518 | \$-32,425 | \$-5,093 |
| 10 | \$-59,004 | \$-58,491 | \$-513 |

### Largest losses of profit contribution

<details><summary>Five largest adverse vault-PnL changes at each wider breadth</summary>

Compare each fixed-score portfolio with six positions. Mean weights are time averages over the full period, so brief large exposures can look small in this column.

| Positions | Vault | Six-position PnL (USD) | Wider PnL (USD) | PnL change (USD) | Six-position mean weight | Wider mean weight |
| --- | --- | --- | --- | --- | --- | --- |
| 7 | Pepe vs  | \$0 | \$-7,211 | \$-7,211 | 0.00% | 0.09% |
| 7 | Realist Capital | \$24,749 | \$18,718 | \$-6,032 | 8.48% | 5.72% |
| 7 | 500 to 1M | \$0 | \$-3,766 | \$-3,766 | 0.00% | 0.34% |
| 7 | pmalt | \$7,576 | \$4,773 | \$-2,803 | 13.07% | 10.44% |
| 7 | Delta_01 | \$948 | \$-1,703 | \$-2,651 | 0.41% | 0.37% |
| 8 | Realist Capital | \$24,749 | \$8,688 | \$-16,061 | 8.48% | 3.76% |
| 8 | pmalt | \$7,576 | \$1,181 | \$-6,395 | 13.07% | 7.67% |
| 8 | DOEZOE | \$11,137 | \$5,685 | \$-5,452 | 1.35% | 1.46% |
| 8 | 500 to 1M | \$0 | \$-3,876 | \$-3,876 | 0.00% | 0.23% |
| 8 | Hyperrr | \$5,233 | \$1,760 | \$-3,473 | 3.10% | 1.23% |
| 10 | Realist Capital | \$24,749 | \$820 | \$-23,929 | 8.48% | 1.91% |
| 10 | DOEZOE | \$11,137 | \$1,588 | \$-9,549 | 1.35% | 0.49% |
| 10 | pmalt | \$7,576 | \$538 | \$-7,038 | 13.07% | 4.15% |
| 10 | Hyperrr | \$5,233 | \$564 | \$-4,669 | 3.10% | 0.61% |
| 10 | Citadel | \$2,879 | \$-821 | \$-3,700 | 14.36% | 12.50% |

</details>

### Largest individual position losses and curator flags

<details><summary>Eight largest losing positions across the four focal variants</summary>

Position profits use the executed ledger and marked holdings. Existing curator flags are descriptive; a false flag does not certify data quality. No post-hoc exclusions are applied to reported strategy results.

| Positions | Vault | Opened | Closed | Final profit (USD) | Curator excluded | Quarantined at entry |
| --- | --- | --- | --- | --- | --- | --- |
| 7 | Pepe vs  | 2026-07-08 | 2026-07-10 | \$-7,211 | False | False |
| 8 | DOEZOE | 2026-09-04 | 2026-09-14 | \$-3,899 | False | False |
| 6 | Realist Capital | 2026-06-06 | 2026-06-16 | \$-3,697 | False | False |
| 8 | 500 to 1M | 2026-03-08 | 2026-03-14 | \$-3,509 | False | False |
| 7 | Realist Capital | 2026-06-12 | 2026-06-16 | \$-3,388 | False | False |
| 10 | songer1993.hl | 2026-09-22 | 2026-09-24 | \$-3,315 | False | False |
| 8 | songer1993.hl | 2026-09-22 | 2026-09-24 | \$-3,315 | False | False |
| 6 | Goon Edging | 2026-02-22 | 2026-03-06 | \$-3,272 | False | False |

</details>