# Experiment 11 — risk estimation, weighting and position sizing

Based on [experiment 10](10-research-portfolio-snapshots.ipynb) and the [reviewed plan](11-weighting-sizing-plan.md), co-designed with Claude CLI fable 5.1.

## Goal and method

Improve weighting and sizing while keeping the selected vaults fixed. Determine whether inverse-variance performance comes from its risk horizon, strength of the allocation preference, shrinkage towards a peer prior, score transformation or subsequent entry constraints. Seek a sensible parameter neighbourhood rather than one best historical cell. Freeze six-vault **focal_four** and **v11** baskets, their eligibility, missing-score tiers and tie-breaking.

Compare risk windows 45/90/180 days, allocation powers 1/1.5/2, fixed kappa 30 versus inherited L/3, raw and regularised risk, bounded inverse-risk scores, median/maximum multi-window forecasts and matched calendar-log/gap-scaled sparse estimators. Risk is calculated on the full eligible universe before selecting baskets. Only NAV is causally forward-filled; actual updates and permission/capacity clocks remain separate. Young/partial histories use the declared peer prior and whole-basket equal fallback, without changing selection.

## Calendar and scope

**2026-01-01 → 2026-10-05, exclusive end, naive UTC**. Four-day cadence gives **70 origins**. Features end at T−1; all 2025 and earlier warmup is retained. Fixed units use inherited anchor NAV(T−1) and terminal NAV(T−1+h). This convention ensures NB10 parity; it is not an executable claim of filling yesterday’s NAV at today’s decision. Mature counts are **68/62/47** for 7/30/90 days, with 2/8/23 pending. Targets require vault-specific terminal support; unresolved holdings stay unresolved.

The **18-policy smoke** is a correctness checkpoint over the full calendar at 30 days. After it passes, the **40-policy main study** reuses those allocations and evaluates all three horizons: 2,800 allocations and 8,400 scheduled outcomes. Twelve sensitivities and eight cap-aware policies are registered, not executed. Historical outcomes are descriptive: primary 30-day inference has at most eight complete blocks, below the required ten. Overlapping snapshots must not be compounded into strategy CAGR.

## Key new insights

The original focal 90/p2 policy leads all nine core window/power cells. Gap-scaled focal sizing gives **2.579% mean 30-day return versus 2.512% for the baseline**, but its median is lower. T18 improves on V180-only sizing by **0.359 percentage points**, chiefly in Q1. Risk calibration and profitable sizing do not always agree. Cash is identical across sizing methods within each selector.

## Summary of results

Completed **18-policy smoke and 40-policy main**, all 70 origins and 7/30/90-day horizons: **2,800 allocations / 8,400 scheduled outcomes**. Mature/resolved counts are 68/68, 62/62 and 47/46. Exact historical controls reproduce. All **17 numerical fixtures,22 smoke and26 main checks pass**. The notebook has 27 separate main charts plus one smoke chart and no logged warnings. Twelve sensitivities and eight cap-aware policies remain registered, unexecuted.

## Robustness of results

All 2025/earlier warmup is retained. No future availability controls selection. Sparse/partial/flat fixtures, exact source controls, future-state mutation, signed unresolved bounds, capacity conservation and same-budget effects pass. The 17 January 90-day Dobutsu–Alpha Club target remains unresolved rather than inventing future NAV. Primary inference has only eight complete blocks, so conclusions remain descriptive. Vault effects offset strongly; T18's gain is regime-sensitive. Fixed-unit anchor fills and retrospective inventory/publication clocks limit production interpretation.

See [findings](11-weighting-sizing-findings.md) and [folder summary](summary.md#nb11--risk-estimation-weighting-and-position-sizing) for hypotheses, outcomes and next steps.

In [1]:
from pathlib import Path
import sys
import pandas as pd
from IPython.display import display, Markdown
ROOT=Path.cwd()
if not (ROOT/'sizing_study_design.py').exists():
    ROOT=ROOT/'scratchpad/hyperliquid-vov-2nd'
sys.path.insert(0,str(ROOT))
from sizing_study_design import smoke_registry, main_registry, followups
from sizing_study_data import read_inputs, stage_folder, freeze_baskets, build_risk
from sizing_study_analysis import execute
from sizing_study_audit import fixtures, audit
from sizing_study_report import render_smoke, render_main, write_findings
from score_matrix_visualisation import compact_output
pd.options.display.max_colwidth=None

## Independent mathematical fixtures — 2026-01-01 → 2026-10-05; 30-day horizon; smoke

Check sparse/partial/flat risk, ddof1, priors, shrinkage, log-space powers, gap drift, fixed-unit paths, unresolved bounds and exact registry counts independently before inspecting returns.

In [2]:
fixture_results=fixtures()
display(fixture_results)

,check,passed,description
0,Partial and sparse simple variance,True,"Three elapsed returns [0.1,0,0.1], two actual updates, ddof1"
1,Flat versus unavailable,True,An actual update is needed; filled zeros alone are insufficient
2,Positive leave-one-out full prior,True,"Self, flat and missing excluded; complete pool preferred"
3,Fixed shrinkage and prior-only fallback,True,Thirty real updates gives half empirical weight; missing gives none
4,Inherited kappa companion,True,L180 inherited strength differs from core kappa30
5,Raw floor asymmetry,True,Regularised estimator has no raw variance floor
6,Log-space allocation power,True,Inverse volatility and variance odds calculated independently
7,Whole-basket equal fallback,True,Unavailable risk retains every selected name
8,Zero-request preserving cap projection,True,Cap redistributes only to positive requests and conserves budget
9,Fixed-unit arithmetic,True,"Cash0.1 plus initial units, no daily rebalancing"
10,Signed unresolved bounds,True,No survivor renormalisation; non-negative NAV only
11,Daily-spacing log estimator identity,True,Gap estimator reduces to sample log variance at one-day spacing
12,Gap-scaled drift centring,True,Constant0.1/day drift across gaps2 and3 has zero model residual variance
13,Sparse support and no invented endpoint,True,At least two complete intervals; trailing fill does not create a final mark
14,QLIKE permits zero realised risk,True,Zero future variance is valid
15,Frozen stage and contrast counts,True,No duplicate equal policies; follow-ups registered only
16,Median forecast before weights,True,Independent multi-window toy calculation

## Pinned inputs and full warmup — 2026-01-01 → 2026-10-05; 30-day horizon; smoke

Verify source archives, metadata, 139 recipes, NB09 features and NB10 component/code hashes. Freeze both baskets once; do not use future availability to alter selection. Earlier generations are read-only.

In [3]:
with compact_output('Read-only inputs and causal risk; estimated one–two minutes'):
    data=read_inputs()
    baskets=freeze_baskets(data)
    risk,support=build_risk(data)
display(pd.DataFrame([{'Origins':len(data['origins']),'Recorded NAV start':str(data['daily'].date.min()),'Frozen recipes':len(data['registry']),'Unique frozen baskets':baskets.groupby(['origin_at','selector']).ngroups,'Unique risk estimates':len(risk)}]))

Read-only inputs and causal risk; estimated one–two minutes — complete

,Origins,Recorded NAV start,Frozen recipes,Unique frozen baskets,Unique risk estimates
0,70,2023-03-01 00:00:00,139,140,114318

## Full-calendar smoke checkpoint — 2026-01-01 → 2026-10-05; 30-day horizon; smoke

Run all 18 registered methods at 70 dates, then compare exact saved controls and per-vault ledgers. Advance based on correctness rather than profitability. A separate chart shows the earliest mechanically cap-active example.

In [4]:
smoke_policies=smoke_registry()
stage_folder(data,smoke_policies,'smoke')
with compact_output('18-policy full-calendar smoke; estimated under two minutes'):
    smoke=execute(data,baskets,risk,smoke_policies,[30])
    smoke_audit=audit(data,smoke,smoke_policies,[30])
smoke_figures=render_smoke(data,smoke,smoke_audit)
display(pd.DataFrame([{'Smoke checks passed':int(smoke_audit.passed.sum()),'Numerical fixtures passed':int(fixture_results.passed.sum()),'Smoke allocations':18*70,'Smoke target rows':len(smoke['outcomes'])}]))

18-policy full-calendar smoke; estimated under two minutes — complete

### Saved control reproduction — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; smoke

Exact NB10 per-date weights and outcomes, using unchanged archive and feature fingerprints.

### 18-policy smoke checkpoint — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; smoke

Full calendar is retained; 62 mature 30-day origins per arm. This checks implementation, not profitability.

### Smoke cap-active example — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; smoke

Earliest focal baseline date with positive cap distortion: 2026-01-01. Chosen from allocation mechanics before inspecting returns.

,Smoke checks passed,Numerical fixtures passed,Smoke allocations,Smoke target rows
0,22,17,1260,1260

## Complete main matrix — 2026-01-01 → 2026-10-05; 7/30/90-day horizons; main

Reuse all 18 smoke allocations and add the 22 remaining registered methods. Allocate once per origin/policy; only future valuation changes with horizon. Save pending dates, terminal censoring, calibration and matched effects.

In [5]:
policies=main_registry()
stage_folder(data,policies,'main')
with compact_output('40 policies,70origins,three horizons; estimated two–five minutes'):
    result=execute(data,baskets,risk,policies,[7,30,90],reuse=smoke)
    main_audit=audit(data,result,policies,[7,30,90],reuse=smoke)
    support.to_parquet(data['artifact']/'risk_pool_support.parquet',index=False)
display(pd.DataFrame([{'Policies':len(policies),'Origin-policy allocations':40*70,'Scheduled outcomes':len(result['outcomes']),'Main audit checks passed':int(main_audit.passed.sum()),'Execution seconds':data['execution_seconds']}]))

40 policies,70origins,three horizons; estimated two–five minutes — complete

,Policies,Origin-policy allocations,Scheduled outcomes,Main audit checks passed,Execution seconds
0,40,2800,8400,26,26.455589

## Results and mechanisms — 2026-01-01 → 2026-10-05; 30-day primary horizon; main

Every table and figure has a separate heading and explanation. Main displays use 30 days; explicitly titled 7/90-day tables are secondary. Colour scales match across comparable cells, and pending/unsupported cells remain grey.

In [6]:
figures=render_main(data,result,main_audit,policies,support)

### Calendar and maturity — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon; main

All 70 origins retained at each horizon; features use T−1 and full 2025/earlier warmup. Pending targets are never zero returns.

### Maturity versus terminal support — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon; main

Administrative maturity does not guarantee supported terminal NAV. Seven/30-day outcomes resolve 68/62 dates; 90-day resolves 46 of 47 mature origins. Unsupported invested weight remains unresolved.

### Unresolved 90-day target — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 90-day horizon; main

Selected using only past information. The target ends beyond this vault’s final actual positive mark; NAV is not carried past terminal support for target evaluation.

### F executed design — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

F = focal_four, L = v11; six frozen vaults. All methods share source-report-only caps, $150k account, 98% budget and 33% concentration/TVL limits. Regularised risk has no raw floor; sparse kappa counts complete intervals.

### L executed design — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

F = focal_four, L = v11; six frozen vaults. All methods share source-report-only caps, $150k account, 98% budget and 33% concentration/TVL limits. Regularised risk has no raw floor; sparse kappa counts complete intervals.

### Exact reference controls — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Saved original/expanded NB10 identities, weights and 62 mature outcomes reproduce. Controls are not independent replications.

### Independent checks — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Mathematics, causal cutoffs, frozen selections, exact controls, maturity and all-origin allocation conservation.

### F side-by-side outcomes — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Equal-origin mean/median snapshot returns, daily portfolio variance and mean within-window drawdown. Cash uses the same resolved mature support; colouring shares scales across selectors. These are not CAGR.

### L side-by-side outcomes — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Equal-origin mean/median snapshot returns, daily portfolio variance and mean within-window drawdown. Cash uses the same resolved mature support; colouring shares scales across selectors. These are not CAGR.

### 17 registered primary contrasts — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

New minus 90-day/p2/kappa30 baseline, plus T18 minus V180. Variance ratio uses ratio of paired mean variances. Eight complete 30-day blocks fail the ten-block gate; all 51 statistics are descriptive.

### Other registered mechanism contrasts — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Paired differences against each selector’s 90-day/p2 baseline, or the named sparse/window control. Common-budget reprojection uses the smaller accepted budget fixed before targets; all main policies happen to invest the same total budget within each selector.

### 7-day secondary outcomes — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7-day horizon; main

Exactly the same allocations as the primary horizon. Horizon maturity changes available quarters; no horizon is promoted to confirmation.

### 90-day secondary outcomes — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 90-day horizon; main

Exactly the same allocations as the primary horizon. Horizon maturity changes available quarters; no horizon is promoted to confirmation.

### F window × power: return difference — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Rows are calendar lookback days; columns p=1 inverse volatility, 1.5 intermediate, 2 inverse variance. Fixed kappa30. Paired resolved dates only; baseline L90/p2. Shared scales across selectors; cell n is pair count.

### F window × power: drawdown difference — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Rows are calendar lookback days; columns p=1 inverse volatility, 1.5 intermediate, 2 inverse variance. Fixed kappa30. Paired resolved dates only; baseline L90/p2. Shared scales across selectors; cell n is pair count.

### F window × power: variance ratio — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Rows are calendar lookback days; columns p=1 inverse volatility, 1.5 intermediate, 2 inverse variance. Fixed kappa30. Paired resolved dates only; baseline L90/p2. Shared scales across selectors; cell n is pair count.

### L window × power: return difference — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Rows are calendar lookback days; columns p=1 inverse volatility, 1.5 intermediate, 2 inverse variance. Fixed kappa30. Paired resolved dates only; baseline L90/p2. Shared scales across selectors; cell n is pair count.

### L window × power: drawdown difference — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Rows are calendar lookback days; columns p=1 inverse volatility, 1.5 intermediate, 2 inverse variance. Fixed kappa30. Paired resolved dates only; baseline L90/p2. Shared scales across selectors; cell n is pair count.

### L window × power: variance ratio — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Rows are calendar lookback days; columns p=1 inverse volatility, 1.5 intermediate, 2 inverse variance. Fixed kappa30. Paired resolved dates only; baseline L90/p2. Shared scales across selectors; cell n is pair count.

### F return and realised risk — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

All registered policies for this selector. Labels identify controls; full formula-to-arm mapping is above. Envelope is descriptive, not a promoted optimum.

### L return and realised risk — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

All registered policies for this selector. Labels identify controls; full formula-to-arm mapping is above. Envelope is descriptive, not a promoted optimum.

### F mean snapshots by origin quarter — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Mean 30-day return, not quarterly profit. Q4 has no mature observations and is grey; n is resolved mature support. Q3 only partly matured.

### L mean snapshots by origin quarter — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Mean 30-day return, not quarterly profit. Q4 has no mature observations and is grey; n is resolved mature support. Q3 only partly matured.

### Breadth, fallback and cap activity — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Shadow at the same accepted budget is a diagnostic, not another evaluated policy. Distortion is sum absolute accepted-minus-shadow weights over all 70 scheduled dates. Outcome cash uses resolved mature dates.

### S01 allocations on 2026-01-01 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Earliest focal baseline cap-active origin, chosen mechanically. Cash 2.00%. Requested shadow uses this method’s own accepted budget.

### S03 allocations on 2026-01-01 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Earliest focal baseline cap-active origin, chosen mechanically. Cash 2.00%. Requested shadow uses this method’s own accepted budget.

### Accepted weights and actual updates in original 90-day window — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Baseline selected vault/date observations on all 70 scheduled origins. Filled NAV days do not create updates; these associations describe reporting support, not predictive independence.

### Forecast risk and actual updates / 90 elapsed days — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Baseline selected vault/date observations on all 70 scheduled origins. Filled NAV days do not create updates; these associations describe reporting support, not predictive independence.

### Accepted weights and elapsed vault history (days) — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Baseline selected vault/date observations on all 70 scheduled origins. Filled NAV days do not create updates; these associations describe reporting support, not predictive independence.

### Accepted weights and age of latest mark at decision (days) — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Baseline selected vault/date observations on all 70 scheduled origins. Filled NAV days do not create updates; these associations describe reporting support, not predictive independence.

### Accepted weights and longest observed internal gap (days) — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Baseline selected vault/date observations on all 70 scheduled origins. Filled NAV days do not create updates; these associations describe reporting support, not predictive independence.

### Full eligible-universe risk support — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Counts use unique estimator/vault/origin rows before selection. Partial is not missing. Sparse m counts complete intervals, whereas original m counts updates. Regularised floors are absent.

### Risk forecast calibration — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Unique selected-vault forecasts, deduplicated across powers/transforms. QLIKE difference versus the same peer prior is averaged within origin then equally across origins. Ratio is mean realised / mean forecast in matched simple/log units.

### F risk forecasting versus prior — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Negative loss difference is better. Daily simple-return and log-return forecasts have matched targets; compare sparse methods only within their common-prior pair. Extreme raw-floor losses remain visible.

### L risk forecasting versus prior — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Negative loss difference is better. Daily simple-return and log-return forecasts have matched targets; compare sparse methods only within their common-prior pair. Extreme raw-floor losses remain visible.

### F baseline variance calibration — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Selected-vault/date points, descriptive only. Log axes omit 0 valid zero realised variances; these zeros remain included in QLIKE and calibration table. Diagonal means exact calibration.

### L baseline variance calibration — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Selected-vault/date points, descriptive only. Log axes omit 0 valid zero realised variances; these zeros remain included in QLIKE and calibration table. Diagonal means exact calibration.

### Matched sparse empirical variance — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Same endpoints, intervals and peer prior; log scale displays positive empirical pairs. Missing and valid zeros are in support tables. Gap estimator assumes variance proportional to elapsed days; it is not ground truth.

### Filled versus strict actual-endpoint support — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Original full status permits carried boundary NAV; sparse pair requires actual marks at both requested endpoints. Peer positive-count and fallback details are saved for all origins.

### Prior-pool endpoint support — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

These are eligible-universe counts, not selected-vault metric coverage. Strict actual-endpoint full pools can be small; both sparse estimators share calendar-log leave-one-out partial-pool fallback.

### Inherited versus fixed prior strength — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

All eligible vault/date forecasts. L/3 changes prior strength with the window; core surface keeps kappa30 fixed. Histogram bins40 are display resolution only.

### Multi-window risk disagreement — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Aggregate variances before inverse-variance sizing. All three positive forecasts are required; partial/prior-only positive estimates remain available. Diagonal means no window disagreement.

### T18 minimum-component activity — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Selected v11 vault/date observations across all 70 origins. Ties split attribution equally; missing components are zero under frozen M0 semantics. V180 uses inherited kappa60, not core kappa30.

### Tail and first-update attribution — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Predeclared baseline/sparse/T18 probes. First actual update strictly after the anchor and remaining NAV contribution sum to return; extreme windows can dominate means.

### Largest vault contributions — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Three largest absolute contributions for each predeclared probe. Mean contribution uses the full resolved calendar; conditional contribution uses only dates held. Removing a contribution does not select a new basket.

### Quarter-removal influence — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Difference from full-calendar mean when one origin quarter is omitted, holding baskets fixed. Grey Q4 means no mature data to remove. This is a regime diagnostic, not a new period selection.

### Paired mechanism effects by origin quarter — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Predeclared sparse/baseline and T18/V180 probes. Common matched dates, fixed baskets; Q4 has no mature labels. First-update column includes the first actual mark strictly after the anchor.

### Selector dependence — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

All scheduled origins. Basket identity overlap and shared capital are continuous descriptive measures; selectors are related robustness contexts.

### Next-stage inventory — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon; main

Exact policies saved in followups.json. No return-based automatic expansion and no shuffled-weight placebos.

## Verdict and registered next work — 2026-01-01 → 2026-10-05; 30-day horizon; main

Write findings only after the 40-policy study and its exact control checks finish. No sensitivities or cap-aware follow-up optimisation are run. Results describe searched historical snapshots, not an executable production return.

In [7]:
findings_path=write_findings(data,result,main_audit)
display(Markdown(f'[Detailed findings]({findings_path.name})'))
display(pd.DataFrame([{'Main checks passed':int(main_audit.passed.sum()),'Separate main figures':len(figures),'Sensitivity policies not run':len(followups()['sensitivities']),'Cap-aware policies not run':len(followups()['cap_aware']),'Generation':data['fingerprint']}]))

[Detailed findings](11-weighting-sizing-findings.md)

,Main checks passed,Separate main figures,Sensitivity policies not run,Cap-aware policies not run,Generation
0,26,27,12,8,b64b9738eff5af379f16d62b65e0147ce2ee4ab8143505b6fb42c864e37f161c