# Experiment 10 — sorting, risk estimation and portfolio allocation snapshots

## Goal and method

Understand whether our frozen scoring methods select profitable vaults, whether risk forecasts anticipate future risk, and whether weighting, breadth and capacity improve construction. This implements [the reviewed plan](10-portfolio-snapshot-plan.md), building on [09](09-research-k-ratio-feature-forecasts.ipynb) and [08](08-research-score-forecast-thresholds.ipynb) inputs. It introduces no new score features or fitted score coefficients.

Every four days we construct an independent basket using completed inputs through T−1, then hold fixed units for 7, 30 or 90 days. There is no inherited strategy state or daily weight rebalancing. IC measures ordering; matched-basket return and variance differences measure allocation effects. These snapshots do not produce executable strategy CAGR or one backtest Sharpe.

Sparse positive NAV is forward-filled causally with actual observation counts and clocks kept separate. Young vaults retain partial risk histories and contemporaneous leave-one-out peer priors; missing scores remain a distinct lowest-ranked tier. Unresolved future outcomes censor the complete selected basket, without replacing vaults or renormalising survivors.

Primary display period: **2026-01-01 → 2026-10-05 (end exclusive, UTC)**. Secondary full/pre-2026 history is explicitly labelled. The plan's ten-block reporting gate makes 2026 descriptive. All inspected history is retrospective research, including longer-period exploratory intervals.

## Results

Completed on 10 October 2026 using the unchanged repaired archive. Future-return score IC is modest (about 0.087–0.089), while selected-basket risk IC is stronger (about 0.51–0.55). Uncapped inverse variance lowers risk but loses30-day return versus equal weights. Peer regularisation moderates that loss; concentration/TVL projection materially changes the comparison. Increasing six to ten positions lowers matched returns and risk. These are independent gross-NAV snapshots, not an executable strategy backtest.

2026 results remain descriptive: the ten-complete-calendar-block gate is unmet. Supported longer-history simultaneous bands include zero, and the periods have already been researched. Sparse/missing histories retain separate observed clocks and explicit support. Independent original-archive and adverse-fixture audits pass; 47 figures have been inspected separately. Full [findings](10-portfolio-snapshot-findings.md) and [risk](appendices/10-snapshot-risk-tables.ipynb), [allocation](appendices/10-snapshot-allocation-tables.ipynb) and [statistical](appendices/10-snapshot-statistics-tables.ipynb) appendices explain support and limitations.

In [1]:
from pathlib import Path
import sys
import pandas as pd
from IPython.display import display, Markdown
ROOT = Path.cwd()
if not (ROOT / 'portfolio_snapshot_data.py').exists():
    ROOT = ROOT / 'scratchpad/hyperliquid-vov-2nd'
sys.path.insert(0, str(ROOT))
from portfolio_snapshot_data import load_inputs, CONFIG, ARTIFACT
from portfolio_snapshot_risk import build_risk
from portfolio_snapshot_construction import run_snapshots
from portfolio_snapshot_pipeline import execute_stage
from score_matrix_visualisation import compact_output

## Frozen design — 2026-01-01 → 2026-10-05; 7/30/90-day horizons

The controls separate sorting, risk forecasts, unequal weights and breadth. The main comparison uses six positions and a 90-day risk window; these are reference settings, not an established optimum.

In [2]:
display(pd.DataFrame([
    ('Scores', 'v11; Blend 46d; four-input focal'),
    ('Risk windows', '30, 60, 90, 180 days; local 75/105-day checks'),
    ('Weight powers', '0 / 0.5 / 1 / 2; p=0 deduplicated equal weights'),
    ('Breadth', '4 / 6 / 8 / 10 requested; retain actual candidate-limited breadth'),
    ('Risk', 'Raw daily variance; support-weight regularisation; source-candle control'),
    ('Sparse history', 'Causal daily carry; no leading backfill; real updates counted separately'),
    ('Capacity', '$150,000; 98% budget; 33% concentration/TVL; unknown-state policies separate'),
    ('Uncertainty', '1,999 calendar-block draws; ten-block gate; fixed 18-contrast family'),
], columns=['Choice', 'Definition']))

           Choice                                         Definition
0          Scores                   v11; Blend 46d; four-input focal
1    Risk windows      30, 60, 90, 180 days; local 75/105-day checks
2   Weight powers    0 / 0.5 / 1 / 2; p=0 deduplicated equal weights
3         Breadth  4 / 6 / 8 / 10 requested; retain actual candid...
4            Risk  Raw daily variance; support-weight regularisat...
5  Sparse history  Causal daily carry; no leading backfill; real ...
6        Capacity  $150,000; 98% budget; 33% concentration/TVL; u...
7     Uncertainty  1,999 calendar-block draws; ten-block gate; fi...

## Pinned population and causal clocks — 2026-01-01 → 2026-10-05; 7/30/90-day horizons

Use the repaired archive already used by experiments 08/09. Original observations supply NAV history; frozen source eligibility and recipes supply selection. Alternate grid phases recompute only those same three recipes, without an engine backtest.

In [3]:
with compact_output('Pinned data and four origin phases'):
    data = load_inputs(include_phases=True)

Pinned data and four origin phases — complete

## Risk inputs — 2026-01-01 → 2026-10-05; 7/30/90-day horizons

Estimate calendar-return variance using available elapsed history. Shrink towards a positive leave-one-out eligible-peer median with confidence m/(m+L/3), where m counts actual daily updates. A one-mark flat carry is unknown risk, not measured zero variance.

In [4]:
with compact_output('Shared causal risk tensors'):
    risk = execute_stage('risk', data)

Shared causal risk tensors — complete

## Independent fixed-unit portfolios — 2026-01-01 → 2026-10-05; 7/30/90-day horizons

Each arm uses a basket selected before future labels are joined. Whole-basket equal fallback and candidate-limited dates remain in policy comparisons. Entry caps affect initial deployment; the portfolio then drifts without rebalancing.

In [5]:
with compact_output('Stages R/W/N/C and bounded companions'):
    result = execute_stage('snapshots', data, risk)

Stages R/W/N/C and bounded companions — complete

## Paired analysis — 2026-01-01 → 2026-10-05; 30-day primary horizon

Preserve the calendar when resampling paired effects. Assignment placebos retain the exact weight multiset; pooled nulls keep seeded identity priorities across dates. Exact breadth and first-update decompositions identify where apparent improvements come from.

In [6]:
with compact_output('Paired inference and mechanism diagnostics'):
    result = execute_stage('statistics', data, risk, result)

Paired inference and mechanism diagnostics — complete

## Independent calculation audit — 2026-01-01 → 2026-10-05; 7/30/90-day horizons

Adverse fixtures and direct original-archive reconstructions check filling, timestamps, source weights, held units, missing targets and exact attribution. Expected values are computed independently of the implementation being checked.

In [7]:
from portfolio_snapshot_audit import run_audit
with compact_output('Independent sparse, timing and portfolio audit'):
    audit = run_audit(data, risk, result, ARTIFACT)
display(audit)

Independent sparse, timing and portfolio audit — complete

,check,status,detail
0,Independent adverse fixture expectations,pass,Leading gap; carried-anchor actual counts; ter...
1,Risk estimator fixtures,pass,Elapsed partial history; carried-anchor real u...
2,Construction and capacity fixtures,pass,Finite zero vs unscored; canonical ties; whole...
3,Calendar support and inference fixtures,pass,Calendar gaps retained; non-overlapping interv...
4,Covariance allocation fixtures,pass,Analytical diagonal/MV/ERC; unknown-risk fallb...
5,Signed missing-return bounds,pass,Positive/negative unknown active weights produ...
6,Synthetic reporting invariants,pass,180 returns / 181 NAV anchors align; every den...
7,Future-price and reporting-mask mutation,pass,72 historical risk/prior rows identical after ...
8,Source capacity companion controls,pass,"All 9 companion arms; 2,817 ledgers preserve b..."
9,Original archive calendar,pass,19 independently reconstructed rows/cases
10,Original archive risk,pass,27 independently reconstructed rows/cases
11,Original archive and NB08 targets,pass,222 independently reconstructed rows/cases
12,Frozen source score cutoff,pass,54 independently reconstructed rows/cases
13,Original fixed-unit snapshot ledger,pass,63 independently reconstructed rows/cases

In [8]:
from portfolio_snapshot_report import render_report
render_report(data, risk, result, audit)

### Pinned inputs — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

The archive and metadata hashes are verified before calculations. Full source/framework fingerprints and every modelling choice are saved in the manifest.

### Declared assumptions — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

These are frozen design choices and numerical conventions, not learned optimal parameters. The complete register is available in the expandable element below.

### Administrative label maturity — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon

Late scheduled origins remain in the origin/selection ledger but cannot have completed future labels inside the archive boundary. Evaluation population denominators below include only administratively mature origins.

### Population and outcome coverage — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon

Denominators are eligible vault/date rows, not only the selected basket. A carried NAV is usable for valuation but is not a new independent observation.

### Six-position reference outcomes — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Mean simple 30-day returns and daily path variances describe independent snapshots. Weighting lift compares the same selected basket and budget with equal weights; no strategy CAGR is inferred.

### Available risk history — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Rows are eligible vault/date observations for the 90-day window on phase zero. Actual updates m determine shrinkage support; calendar returns n do not manufacture observations.

### Risk ordering across the eligible universe — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon

StageR evaluates every eligible vault, including missing composite scores. Equal-date risk IC is conditional on observed finite risk targets. Eligible membership is common to all frozen scores; one nonduplicated panel is shown. Cell support: 47–68 origins;2026 estimates are descriptive under the ten-block gate.

### Eligible versus selected risk forecasts — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Selected rows use the exact frozen top-six basket, where weighting operates. Risk accuracy and support may change at the selection boundary; the eligible panels are common to all three scoring methods.

### Risk ordering: v11 top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Equal-date Spearman correlation with future daily variance; higher is stronger risk ordering. Grey cells lack computable support. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk ordering: Blend 46d top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Equal-date Spearman correlation with future daily variance; higher is stronger risk ordering. Grey cells lack computable support. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk ordering: Four-input focal top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Equal-date Spearman correlation with future daily variance; higher is stronger risk ordering. Grey cells lack computable support. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk forecast loss versus peer prior: v11 top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Paired QLIKE differences use identical vault/date targets; negative is better. The symmetric log colour scale exposes extreme floor errors without clipping them. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk forecast loss versus peer prior: Blend 46d top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Paired QLIKE differences use identical vault/date targets; negative is better. The symmetric log colour scale exposes extreme floor errors without clipping them. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk forecast loss versus peer prior: Four-input focal top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Paired QLIKE differences use identical vault/date targets; negative is better. The symmetric log colour scale exposes extreme floor errors without clipping them. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk level calibration: v11 top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Ratio of equal-date predicted to realised mean variance. One indicates matching mean risk levels; zero realised variance remains zero and no epsilon is added. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk level calibration: Blend 46d top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Ratio of equal-date predicted to realised mean variance. One indicates matching mean risk levels; zero realised variance remains zero and no epsilon is added. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk level calibration: Four-input focal top six — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Ratio of equal-date predicted to realised mean variance. One indicates matching mean risk levels; zero realised variance remains zero and no epsilon is added. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Risk loss concentration — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Each origin has equal weight. The largest 5% of absolute weighted row loss differences show tail sensitivity; they are retained in all primary means. A positive loss difference favours the peer prior.

### Thirty-day selected risk calibration — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Points are equal-date mean predicted and realised daily variance for six-vault regularised forecasts. Log axes are used only on positive values; zero targets are excluded from this plot, retained in loss tables.

### Score versus future return IC — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon

Equal-date finite-pair Spearman correlations describe the observed-outcome association. Missing scores and outcomes are omitted from IC, but retained in portfolio selection/attrition. Cell support: 47–68 origins;2026 estimates are descriptive under the ten-block gate.

### IC support: return — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon

Origin count is the number of computable cross-sections; pair count varies by date. Overlapping horizons are dependent.

### Score versus future vault Sharpe IC — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon

Equal-date finite-pair Spearman correlations describe the observed-outcome association. Missing scores and outcomes are omitted from IC, but retained in portfolio selection/attrition. Cell support: 47–68 origins;2026 estimates are descriptive under the ten-block gate.

### IC support: sharpe — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon

Origin count is the number of computable cross-sections; pair count varies by date. Overlapping horizons are dependent.

### Cross-section support sensitivity — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

The 3/5/10/20 finite-pair gates are descriptive support checks, not significance thresholds.

### Strict universe-reference selection lift — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Positive means selected equal weights beat the entire ex-ante eligible equal universe. Only fully resolved eligible universes qualify; grey means unsupported, never survivor-only replacement. Cell support: 55–55 origins;2026 estimates are descriptive under the ten-block gate.

### Strict selection support — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

The whole eligible-universe benchmark can lose support even when a small selected basket resolves. This stricter estimand is secondary to matched-basket weighting.

### Mean weighting return lift: v11, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Percentage-point simple-return difference from equal weights on exactly the same basket. Positive is higher return. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Daily portfolio variance difference: v11, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Daily simple-return variance difference from equal weights. Negative is lower observed path risk; no annualised strategy Sharpe is inferred. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Snapshot drawdown difference: v11, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Signed maximum-drawdown difference from equal weights. Positive is less severe drawdown on the fixed-unit path. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Mean weighting return lift: v11, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Percentage-point simple-return difference from equal weights on exactly the same basket. Positive is higher return. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Daily portfolio variance difference: v11, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Daily simple-return variance difference from equal weights. Negative is lower observed path risk; no annualised strategy Sharpe is inferred. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Snapshot drawdown difference: v11, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Signed maximum-drawdown difference from equal weights. Positive is less severe drawdown on the fixed-unit path. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Mean weighting return lift: Blend 46d, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Percentage-point simple-return difference from equal weights on exactly the same basket. Positive is higher return. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Daily portfolio variance difference: Blend 46d, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Daily simple-return variance difference from equal weights. Negative is lower observed path risk; no annualised strategy Sharpe is inferred. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Snapshot drawdown difference: Blend 46d, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Signed maximum-drawdown difference from equal weights. Positive is less severe drawdown on the fixed-unit path. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Mean weighting return lift: Blend 46d, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Percentage-point simple-return difference from equal weights on exactly the same basket. Positive is higher return. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Daily portfolio variance difference: Blend 46d, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Daily simple-return variance difference from equal weights. Negative is lower observed path risk; no annualised strategy Sharpe is inferred. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Snapshot drawdown difference: Blend 46d, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Signed maximum-drawdown difference from equal weights. Positive is less severe drawdown on the fixed-unit path. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Mean weighting return lift: Four-input focal, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Percentage-point simple-return difference from equal weights on exactly the same basket. Positive is higher return. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Daily portfolio variance difference: Four-input focal, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Daily simple-return variance difference from equal weights. Negative is lower observed path risk; no annualised strategy Sharpe is inferred. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Snapshot drawdown difference: Four-input focal, raw, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Signed maximum-drawdown difference from equal weights. Positive is less severe drawdown on the fixed-unit path. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Mean weighting return lift: Four-input focal, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Percentage-point simple-return difference from equal weights on exactly the same basket. Positive is higher return. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Daily portfolio variance difference: Four-input focal, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Daily simple-return variance difference from equal weights. Negative is lower observed path risk; no annualised strategy Sharpe is inferred. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Snapshot drawdown difference: Four-input focal, regularised, N=6 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Signed maximum-drawdown difference from equal weights. Positive is less severe drawdown on the fixed-unit path. Equal row is a display alias of one deduplicated policy. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Construction return/risk trade-off — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Each point is one six-vault 90-day policy. X is the square root of mean daily path variance, annualised for scale; Y is mean 30-day simple return. These are snapshot outcomes, not backtest CAGR/Sharpe.

### Trade-off point labels — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Point IDs keep the chart legible. Source and raw controls share a point where their observed outcomes coincide; they are aliases in this chart, not independent evidence.

### Per-origin trade-off by quarter — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

The regularised inverse-variance six-vault control is shown separately by score. Quarter colours reveal whether risk/return relationships change during 2026. Large path outliers remain visible.

### Quarterly origins: v11 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Each dot is a fully resolved fixed-unit 30-day snapshot; overlapping origins are dependent.

### Quarterly origins: Blend 46d — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Each dot is a fully resolved fixed-unit 30-day snapshot; overlapping origins are dependent.

### Quarterly origins: Four-input focal — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Each dot is a fully resolved fixed-unit 30-day snapshot; overlapping origins are dependent.

### Breadth and mean return — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Lines compare requested position counts on origins where all four preselected baskets resolve, with a common regularised 90-day risk estimator. This matched union avoids an apparent improvement from changing outcome support; legend n reports paired origins.

### Breadth and effective invested positions — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Effective N = 1/Σq² measures initial concentration. More requested slots do not imply equally spread capital.

### Exact breadth attribution versus six positions — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

The same-origin difference reconciles to shared-vault reweighting plus added/removed-name contributions at original account notional. Cash contribution is zero in this pure branch.

### Conditional return by individual selection rank — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Observed-target means at every rank through 20. Missing labels do not move a later vault into a missing rank. These conditional means do not replace fully supported basket returns.

### Concentration-matched assignment placebo — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Exact per-date permutations preserve concentration and have equal-weight mean return. Pooled intervals are a persistent seeded-identity assignment null, not confidence intervals for profitability.

### Weight assignment versus persistent-identity null — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Points are actual 30-day return lift over equal weights. Bars show the central 95% of 999 coherent random assignments; date overlap is retained by persistent identity priorities.

### Score assignment null — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

A within-date exchangeability null and a pre-origin age/quality stratified sensitivity test ordering. These per-date permutations are not a null for a persistent portfolio policy.

### Capacity and same-budget weighting — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Source-report-only enforces concentration and TVL, while permissive also applies recorded hard caps as an explicit diagnostic. Known-only refuses unknown clocks/state. Missing fields are not zero capacity; unknown-state exclusion is separately labelled.

### Original-request allocation without redistribution — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Accepted weights are min(cap,98%×desired weight). Residual remains cash. Weighting lift still uses a bounded equal benchmark at the same accepted budget.

### Cash after entry caps: v11 — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Fresh account-size/concentration sensitivity with recorded permissive capacity. These are conditional stateless entry allocations, not live deposit guarantees. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Cash after entry caps: Blend 46d — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Fresh account-size/concentration sensitivity with recorded permissive capacity. These are conditional stateless entry allocations, not live deposit guarantees. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Cash after entry caps: Four-input focal — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Fresh account-size/concentration sensitivity with recorded permissive capacity. These are conditional stateless entry allocations, not live deposit guarantees. Cell support: 62–62 origins;2026 estimates are descriptive under the ten-block gate.

### Desired versus accepted entry weights — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Example origin 2026-01-01: first displayed origin with entry clipping. The equal benchmark shares the accepted total budget; permission/capacity clocks are not filled from price observations.

### Satellite budget versus ordinary widening — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

A fixed six-name core receives 100/90/80% of the invested budget; ranks7–10 receive0/10/20%. Both groups use regularised inverse variance. All points for a score share the same fully resolved union of names/origins; legend n reports support. Dashed levels show ordinary ten-name normalisation, which can allocate a very different satellite share.

### Bounded construction companions — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Satellite groups preserve the same relative risk weights within core and satellite. Correlation methods use Ledoit–Wolf scaled-identity shrinkage rescaled to the same marginal risks; failed support uses an explicitly labelled diagonal prior.

### Basket entry-risk calibration — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Compare initial wᵀΣw (or diagonal counterpart) with subsequent fixed-unit daily variance on matched origins. Both forecast error and position-weight drift affect this target; no constant-mix assumption is made.

### Correlation-estimation support — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

The full support ledger is saved in artefacts. Identity correlation is a prior used when overlap or actual-update support fails; it is not evidence of independence.

### Quarterly weighting lift — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Regularised inverse variance, six positions, 90-day risk. Different origin quarters overlap future paths; positive return lift favours unequal weights.

### Four origin phases — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Each phase repeats the same focal construction on a shifted four-day grid. Phases share outcomes and are sensitivity checks, not four independent replications.

### Horizon-spaced origin diagnostic — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Keep one deterministic sequence of supported origins at least 30 days apart. This diagnostic reduces overlap and does not manufacture multiple holdouts.

### Leave-one-quarter influence — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Re-average the existing fixed snapshot ledger after omitting an origin quarter. This is a sensitivity calculation, not an investable reconstructed strategy.

### Largest vault contributions to weighting lift — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Contribution is active weight versus equal times vault simple return, averaged over all paired origins for that score. Removing a contribution holds the allocation ledger fixed; it does not reselect a portfolio.

### Recorded age and actual reporting coverage — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Every point is an eligible phase-zero vault/date risk row at L=90. Age means recorded positive NAV history, not known vault inception; colour is the age of the latest actual NAV at the origin, in days. Intraday ages remain on the same linear day scale.

### Reporting-boundary attribution — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

The first catch-up mark can include both pre-origin and genuine post-origin movement. Its active-weight contribution plus the remaining original-notional component reconciles exactly; neither is an executable corrected return.

### Unresolved future outcomes — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Any positive-weight missing terminal path censors the basket. Known weighted contributions minus unresolved weight give a lower NAV-return bound; missing upside is unbounded. Break-even common-missing-return scenarios are saved separately and are not identified bounds.

### Largest absolute snapshot moves — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

These are overlapping horizon outcomes, not separate profitable trades. They remain in means; the per-vault contribution and quarter influence tables show whether an advantage is concentrated.

### Tie-resolution sensitivity — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

999 seeded identity priorities per tied origin propagate clipped/missing-score ties into membership and returns. Ranges are conditional tie outcomes, not confidence intervals.

### Basket and target-weight stability — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Consecutive four-day Jaccard overlap and half the absolute desired allocation change, including cash. Missing origins are not compressed; these quantities are not realised turnover or fees.

### Synthetic reporting risk distortion — 2026-01-01 → 2026-10-05 (end exclusive, UTC); Synthetic 180-day histories; 2026 reporting patterns

Known dense processes are masked at daily, two-day and seven-day schedules. Ratio is estimated/dense risk. Regularisation uses known dense risk as a mechanism-isolation prior, not estimated live latent risk. Each process has 180 returns, 100 replicates and κ=60; log-return diffusion mean/σ=0.0002/0.01, alternating amplitude=0.01, and catch-up jump=0.07 every 31 days.

### Primary paired construction contrasts — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

All 18 frozen comparisons remain visible. Return effects are horizon percentage-point differences; variance effects are daily-variance units. 2026 is descriptive under the ten-block gate.

### Horizon stability — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 7/30/90-day horizon

Same frozen regularised six-position inverse-variance construction at 7/30/90 days. Means use each horizon’s fully resolved selected baskets; unequal administrative support must not be mistaken for a horizon effect.

### Secondary Pre-2026 primary contrasts — 2023-03-01 → 2026-01-01 (end exclusive, UTC); 30-day horizon

Simultaneous intervals share calendar blocks across the frozen family. Longer history remains exploratory and overlaps earlier research; the Long period includes 2026.

### Secondary Long primary contrasts — 2023-03-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Simultaneous intervals share calendar blocks across the frozen family. Longer history remains exploratory and overlaps earlier research; the Long period includes 2026.

### Research verdict and next checks — 2026-01-01 → 2026-10-05 (end exclusive, UTC); 30-day horizon

Read the separate findings document for the full hypothesis-by-hypothesis account. The conclusions below concern 30-day 2026 gross-NAV snapshots; they do not identify an executable strategy winner.

- **Sorting:** future-return IC is modest and similar across the three frozen scores (about 0.087–0.089).
- **Risk forecasts:** selected risk IC is stronger (about 0.51–0.55), while calibration and tail losses still require care.
- **Weights:** uncapped inverse variance lowers risk and returns. Regularisation reduces the return drag; concentration/TVL projection can change its sign.
- **Breadth:** matched 10-versus-6-position returns fall as risk falls. Satellite comparisons use the same resolved origins.
- **Uncertainty:** 2026 fails the ten-block gate; supported longer-history simultaneous bands include zero.
- **Next:** replay regularisation × capped redistribution with matched equal controls. Detailed [findings](10-portfolio-snapshot-findings.md), [risk](appendices/10-snapshot-risk-tables.ipynb), [allocation](appendices/10-snapshot-allocation-tables.ipynb) and [statistics](appendices/10-snapshot-statistics-tables.ipynb) appendices preserve the complete results.